// Medicare Advantage Plan Quote Engine — Mock Data
// 24 MA Plans for Jackson County, MO (ZIP 64106)
// Carriers: UHC, Humana, Aetna, Cigna, WellCare, Blue KC

import type { MedicarePlan, Carrier } from "./types";

export const CARRIER_COLORS: Record<Carrier, { bg: string; text: string; border: string }> = {
  UnitedHealthcare: { bg: "#002677", text: "#FFFFFF", border: "#002677" },
  Humana: { bg: "#006D9D", text: "#FFFFFF", border: "#006D9D" },
  Aetna: { bg: "#7D2248", text: "#FFFFFF", border: "#7D2248" },
  Cigna: { bg: "#E8002D", text: "#FFFFFF", border: "#E8002D" },
  WellCare: { bg: "#00A651", text: "#FFFFFF", border: "#00A651" },
  "Blue KC": { bg: "#003087", text: "#FFFFFF", border: "#003087" },
};

export const MOCK_PLANS: MedicarePlan[] = [
  // ─── UnitedHealthcare (4 plans) ───────────────────────────────────────────
  {
    id: "uhc-aarp-1",
    carrier: "UnitedHealthcare",
    planName: "AARP MedicareComplete Choice Plan 1 (PPO)",
    planType: "PPO",
    contractId: "H0609",
    planId: "001",
    starRating: { overall: 4.5, label: "4.5 out of 5" },
    premium: 0,
    partBPremiumReduction: 0,
    deductible: 0,
    maxOutOfPocket: 6700,
    copays: {
      primaryCare: "$0 copay",
      specialist: "$40 copay",
      urgentCare: "$40 copay",
      emergency: "$120 copay",
      inpatientHospital: "$325/day (Days 1–5)",
      outpatientSurgery: "$250 copay",
    },
    rxDrugs: {
      tier1: "$0 copay",
      tier2: "$10 copay",
      tier3: "$47 copay",
      tier4: "$100 copay",
      deductible: "$0",
      gap: true,
      initialCoverageLimit: "$5,030",
    },
    extraBenefits: {
      dental: { covered: true, details: "Comprehensive dental: cleanings, X-rays, fillings, crowns", annualLimit: "$2,000" },
      vision: { covered: true, details: "Annual eye exam + $200 eyewear allowance" },
      hearing: { covered: true, details: "$1,500 hearing aid allowance every 3 years" },
      otc: { covered: true, details: "$100/quarter OTC benefit card", annualLimit: "$400/year" },
      fitness: { covered: true, details: "Renew Active gym membership included" },
      transportation: { covered: true, details: "24 one-way trips/year to medical appointments" },
      telehealth: { covered: true, details: "$0 virtual visits 24/7" },
      meals: { covered: false, details: "Not covered" },
    },
    networkSize: 4200,
    isBestMatch: true,
    isMostPopular: true,
    enrollmentPeriod: "Oct 15 – Dec 7",
    effectiveDate: "Jan 1, 2025",
    serviceArea: "Jackson County, MO",
    carrierLogoColor: "#002677",
    carrierLogoTextColor: "#FFFFFF",
  },
  {
    id: "uhc-aarp-2",
    carrier: "UnitedHealthcare",
    planName: "AARP MedicareComplete Patriot (HMO)",
    planType: "HMO",
    contractId: "H0609",
    planId: "003",
    starRating: { overall: 4.5, label: "4.5 out of 5" },
    premium: 0,
    partBPremiumReduction: 0,
    deductible: 0,
    maxOutOfPocket: 4900,
    copays: {
      primaryCare: "$0 copay",
      specialist: "$35 copay",
      urgentCare: "$35 copay",
      emergency: "$90 copay",
      inpatientHospital: "$275/day (Days 1–5)",
      outpatientSurgery: "$175 copay",
    },
    rxDrugs: {
      tier1: "$0 copay",
      tier2: "$5 copay",
      tier3: "$42 copay",
      tier4: "$95 copay",
      deductible: "$0",
      gap: true,
      initialCoverageLimit: "$5,030",
    },
    extraBenefits: {
      dental: { covered: true, details: "Preventive dental + $1,500 comprehensive", annualLimit: "$1,500" },
      vision: { covered: true, details: "Annual eye exam + $150 eyewear allowance" },
      hearing: { covered: true, details: "$1,000 hearing aid allowance every 3 years" },
      otc: { covered: true, details: "$75/quarter OTC benefit card", annualLimit: "$300/year" },
      fitness: { covered: true, details: "Renew Active gym membership included" },
      transportation: { covered: true, details: "12 one-way trips/year" },
      telehealth: { covered: true, details: "$0 virtual visits 24/7" },
      meals: { covered: false, details: "Not covered" },
    },
    networkSize: 3100,
    isMostPopular: false,
    enrollmentPeriod: "Oct 15 – Dec 7",
    effectiveDate: "Jan 1, 2025",
    serviceArea: "Jackson County, MO",
    carrierLogoColor: "#002677",
    carrierLogoTextColor: "#FFFFFF",
  },
  {
    id: "uhc-aarp-3",
    carrier: "UnitedHealthcare",
    planName: "AARP MedicareComplete Choice Plan 2 (PPO)",
    planType: "PPO",
    contractId: "H0609",
    planId: "005",
    starRating: { overall: 4.0, label: "4 out of 5" },
    premium: 29,
    partBPremiumReduction: 0,
    deductible: 0,
    maxOutOfPocket: 4000,
    copays: {
      primaryCare: "$0 copay",
      specialist: "$30 copay",
      urgentCare: "$30 copay",
      emergency: "$90 copay",
      inpatientHospital: "$250/day (Days 1–5)",
      outpatientSurgery: "$150 copay",
    },
    rxDrugs: {
      tier1: "$0 copay",
      tier2: "$5 copay",
      tier3: "$40 copay",
      tier4: "$90 copay",
      deductible: "$0",
      gap: true,
      initialCoverageLimit: "$5,030",
    },
    extraBenefits: {
      dental: { covered: true, details: "Comprehensive dental coverage", annualLimit: "$3,000" },
      vision: { covered: true, details: "Annual exam + $250 eyewear allowance" },
      hearing: { covered: true, details: "$2,000 hearing aid allowance" },
      otc: { covered: true, details: "$150/quarter OTC benefit card", annualLimit: "$600/year" },
      fitness: { covered: true, details: "Renew Active gym membership" },
      transportation: { covered: true, details: "36 one-way trips/year" },
      telehealth: { covered: true, details: "$0 virtual visits" },
      meals: { covered: true, details: "28 meals after hospital stay" },
    },
    networkSize: 4200,
    enrollmentPeriod: "Oct 15 – Dec 7",
    effectiveDate: "Jan 1, 2025",
    serviceArea: "Jackson County, MO",
    carrierLogoColor: "#002677",
    carrierLogoTextColor: "#FFFFFF",
  },
  {
    id: "uhc-dual-1",
    carrier: "UnitedHealthcare",
    planName: "Dual Complete Plan (HMO-SNP)",
    planType: "SNP",
    contractId: "H0609",
    planId: "010",
    starRating: { overall: 4.0, label: "4 out of 5" },
    premium: 0,
    partBPremiumReduction: 0,
    deductible: 0,
    maxOutOfPocket: 3450,
    copays: {
      primaryCare: "$0 copay",
      specialist: "$0 copay",
      urgentCare: "$0 copay",
      emergency: "$0 copay",
      inpatientHospital: "$0/day",
      outpatientSurgery: "$0 copay",
    },
    rxDrugs: {
      tier1: "$0 copay",
      tier2: "$0 copay",
      tier3: "$0 copay",
      tier4: "$0 copay",
      deductible: "$0",
      gap: true,
      initialCoverageLimit: "$5,030",
    },
    extraBenefits: {
      dental: { covered: true, details: "Full dental coverage", annualLimit: "Unlimited" },
      vision: { covered: true, details: "Full vision coverage" },
      hearing: { covered: true, details: "Full hearing coverage" },
      otc: { covered: true, details: "$125/month OTC benefit", annualLimit: "$1,500/year" },
      fitness: { covered: true, details: "Gym membership included" },
      transportation: { covered: true, details: "Unlimited trips to medical appointments" },
      telehealth: { covered: true, details: "$0 virtual visits" },
      meals: { covered: true, details: "Meals after hospital stay" },
    },
    networkSize: 3100,
    snpType: "Dual Eligible (D-SNP)",
    enrollmentPeriod: "Year-round",
    effectiveDate: "Jan 1, 2025",
    serviceArea: "Jackson County, MO",
    carrierLogoColor: "#002677",
    carrierLogoTextColor: "#FFFFFF",
  },

  // ─── Humana (4 plans) ─────────────────────────────────────────────────────
  {
    id: "humana-gold-1",
    carrier: "Humana",
    planName: "Humana Gold Plus H5619 (HMO)",
    planType: "HMO",
    contractId: "H5619",
    planId: "001",
    starRating: { overall: 4.0, label: "4 out of 5" },
    premium: 0,
    partBPremiumReduction: 0,
    deductible: 0,
    maxOutOfPocket: 5900,
    copays: {
      primaryCare: "$0 copay",
      specialist: "$40 copay",
      urgentCare: "$40 copay",
      emergency: "$120 copay",
      inpatientHospital: "$350/day (Days 1–5)",
      outpatientSurgery: "$200 copay",
    },
    rxDrugs: {
      tier1: "$1 copay",
      tier2: "$6 copay",
      tier3: "$44 copay",
      tier4: "$100 copay",
      deductible: "$0",
      gap: false,
      initialCoverageLimit: "$5,030",
    },
    extraBenefits: {
      dental: { covered: true, details: "Preventive dental + $1,000 comprehensive", annualLimit: "$1,000" },
      vision: { covered: true, details: "Annual exam + $100 eyewear allowance" },
      hearing: { covered: true, details: "$500 hearing aid allowance" },
      otc: { covered: true, details: "$50/quarter OTC benefit", annualLimit: "$200/year" },
      fitness: { covered: true, details: "SilverSneakers gym membership" },
      transportation: { covered: false, details: "Not covered" },
      telehealth: { covered: true, details: "$0 virtual visits" },
      meals: { covered: false, details: "Not covered" },
    },
    networkSize: 2800,
    isMostPopular: true,
    enrollmentPeriod: "Oct 15 – Dec 7",
    effectiveDate: "Jan 1, 2025",
    serviceArea: "Jackson County, MO",
    carrierLogoColor: "#006D9D",
    carrierLogoTextColor: "#FFFFFF",
  },
  {
    id: "humana-choice-1",
    carrier: "Humana",
    planName: "Humana Choice H5216 (PPO)",
    planType: "PPO",
    contractId: "H5216",
    planId: "002",
    starRating: { overall: 3.5, label: "3.5 out of 5" },
    premium: 0,
    partBPremiumReduction: 0,
    deductible: 0,
    maxOutOfPocket: 7550,
    copays: {
      primaryCare: "$5 copay",
      specialist: "$45 copay",
      urgentCare: "$45 copay",
      emergency: "$120 copay",
      inpatientHospital: "$375/day (Days 1–5)",
      outpatientSurgery: "$225 copay",
    },
    rxDrugs: {
      tier1: "$2 copay",
      tier2: "$8 copay",
      tier3: "$47 copay",
      tier4: "$100 copay",
      deductible: "$100",
      gap: false,
      initialCoverageLimit: "$5,030",
    },
    extraBenefits: {
      dental: { covered: true, details: "Preventive dental only", annualLimit: "$500" },
      vision: { covered: true, details: "Annual exam + $75 eyewear allowance" },
      hearing: { covered: false, details: "Not covered" },
      otc: { covered: false, details: "Not covered" },
      fitness: { covered: true, details: "SilverSneakers gym membership" },
      transportation: { covered: false, details: "Not covered" },
      telehealth: { covered: true, details: "$0 virtual visits" },
      meals: { covered: false, details: "Not covered" },
    },
    networkSize: 3500,
    enrollmentPeriod: "Oct 15 – Dec 7",
    effectiveDate: "Jan 1, 2025",
    serviceArea: "Jackson County, MO",
    carrierLogoColor: "#006D9D",
    carrierLogoTextColor: "#FFFFFF",
  },
  {
    id: "humana-value-1",
    carrier: "Humana",
    planName: "Humana Value Plus (HMO)",
    planType: "HMO",
    contractId: "H5619",
    planId: "015",
    starRating: { overall: 4.0, label: "4 out of 5" },
    premium: 0,
    partBPremiumReduction: 20,
    deductible: 0,
    maxOutOfPocket: 4900,
    copays: {
      primaryCare: "$0 copay",
      specialist: "$35 copay",
      urgentCare: "$35 copay",
      emergency: "$90 copay",
      inpatientHospital: "$295/day (Days 1–5)",
      outpatientSurgery: "$175 copay",
    },
    rxDrugs: {
      tier1: "$0 copay",
      tier2: "$5 copay",
      tier3: "$42 copay",
      tier4: "$95 copay",
      deductible: "$0",
      gap: true,
      initialCoverageLimit: "$5,030",
    },
    extraBenefits: {
      dental: { covered: true, details: "Comprehensive dental", annualLimit: "$2,000" },
      vision: { covered: true, details: "Annual exam + $200 eyewear" },
      hearing: { covered: true, details: "$1,000 hearing aid allowance" },
      otc: { covered: true, details: "$100/quarter OTC", annualLimit: "$400/year" },
      fitness: { covered: true, details: "SilverSneakers included" },
      transportation: { covered: true, details: "12 one-way trips/year" },
      telehealth: { covered: true, details: "$0 virtual visits" },
      meals: { covered: false, details: "Not covered" },
    },
    networkSize: 2800,
    isNewPlan: true,
    enrollmentPeriod: "Oct 15 – Dec 7",
    effectiveDate: "Jan 1, 2025",
    serviceArea: "Jackson County, MO",
    carrierLogoColor: "#006D9D",
    carrierLogoTextColor: "#FFFFFF",
  },
  {
    id: "humana-premier-1",
    carrier: "Humana",
    planName: "Humana Premier Rx Plan (PPO)",
    planType: "PPO",
    contractId: "H5216",
    planId: "020",
    starRating: { overall: 4.5, label: "4.5 out of 5" },
    premium: 49,
    partBPremiumReduction: 0,
    deductible: 0,
    maxOutOfPocket: 3400,
    copays: {
      primaryCare: "$0 copay",
      specialist: "$25 copay",
      urgentCare: "$25 copay",
      emergency: "$75 copay",
      inpatientHospital: "$200/day (Days 1–5)",
      outpatientSurgery: "$125 copay",
    },
    rxDrugs: {
      tier1: "$0 copay",
      tier2: "$4 copay",
      tier3: "$38 copay",
      tier4: "$85 copay",
      deductible: "$0",
      gap: true,
      initialCoverageLimit: "$5,030",
    },
    extraBenefits: {
      dental: { covered: true, details: "Full dental coverage", annualLimit: "$3,500" },
      vision: { covered: true, details: "Annual exam + $300 eyewear" },
      hearing: { covered: true, details: "$2,500 hearing aid allowance" },
      otc: { covered: true, details: "$200/quarter OTC", annualLimit: "$800/year" },
      fitness: { covered: true, details: "SilverSneakers + gym reimbursement" },
      transportation: { covered: true, details: "48 one-way trips/year" },
      telehealth: { covered: true, details: "$0 virtual visits" },
      meals: { covered: true, details: "56 meals after hospital stay" },
    },
    networkSize: 3500,
    isBestMatch: false,
    enrollmentPeriod: "Oct 15 – Dec 7",
    effectiveDate: "Jan 1, 2025",
    serviceArea: "Jackson County, MO",
    carrierLogoColor: "#006D9D",
    carrierLogoTextColor: "#FFFFFF",
  },

  // ─── Aetna (4 plans) ──────────────────────────────────────────────────────
  {
    id: "aetna-medicare-1",
    carrier: "Aetna",
    planName: "Aetna Medicare Advantage Value Plan (HMO)",
    planType: "HMO",
    contractId: "H3312",
    planId: "001",
    starRating: { overall: 3.5, label: "3.5 out of 5" },
    premium: 0,
    partBPremiumReduction: 0,
    deductible: 0,
    maxOutOfPocket: 6700,
    copays: {
      primaryCare: "$5 copay",
      specialist: "$45 copay",
      urgentCare: "$45 copay",
      emergency: "$120 copay",
      inpatientHospital: "$400/day (Days 1–5)",
      outpatientSurgery: "$250 copay",
    },
    rxDrugs: {
      tier1: "$2 copay",
      tier2: "$8 copay",
      tier3: "$47 copay",
      tier4: "$100 copay",
      deductible: "$100",
      gap: false,
      initialCoverageLimit: "$5,030",
    },
    extraBenefits: {
      dental: { covered: true, details: "Preventive dental", annualLimit: "$500" },
      vision: { covered: true, details: "Annual exam + $100 eyewear" },
      hearing: { covered: false, details: "Not covered" },
      otc: { covered: true, details: "$25/quarter OTC", annualLimit: "$100/year" },
      fitness: { covered: true, details: "SilverSneakers gym membership" },
      transportation: { covered: false, details: "Not covered" },
      telehealth: { covered: true, details: "$0 virtual visits" },
      meals: { covered: false, details: "Not covered" },
    },
    networkSize: 2400,
    enrollmentPeriod: "Oct 15 – Dec 7",
    effectiveDate: "Jan 1, 2025",
    serviceArea: "Jackson County, MO",
    carrierLogoColor: "#7D2248",
    carrierLogoTextColor: "#FFFFFF",
  },
  {
    id: "aetna-medicare-2",
    carrier: "Aetna",
    planName: "Aetna Medicare Advantage Choice Plan (PPO)",
    planType: "PPO",
    contractId: "H3312",
    planId: "003",
    starRating: { overall: 4.0, label: "4 out of 5" },
    premium: 0,
    partBPremiumReduction: 0,
    deductible: 0,
    maxOutOfPocket: 7550,
    copays: {
      primaryCare: "$0 copay",
      specialist: "$40 copay",
      urgentCare: "$40 copay",
      emergency: "$120 copay",
      inpatientHospital: "$350/day (Days 1–5)",
      outpatientSurgery: "$200 copay",
    },
    rxDrugs: {
      tier1: "$0 copay",
      tier2: "$6 copay",
      tier3: "$44 copay",
      tier4: "$100 copay",
      deductible: "$0",
      gap: false,
      initialCoverageLimit: "$5,030",
    },
    extraBenefits: {
      dental: { covered: true, details: "Preventive + basic dental", annualLimit: "$1,000" },
      vision: { covered: true, details: "Annual exam + $150 eyewear" },
      hearing: { covered: true, details: "$500 hearing aid allowance" },
      otc: { covered: true, details: "$50/quarter OTC", annualLimit: "$200/year" },
      fitness: { covered: true, details: "SilverSneakers included" },
      transportation: { covered: false, details: "Not covered" },
      telehealth: { covered: true, details: "$0 virtual visits" },
      meals: { covered: false, details: "Not covered" },
    },
    networkSize: 3200,
    enrollmentPeriod: "Oct 15 – Dec 7",
    effectiveDate: "Jan 1, 2025",
    serviceArea: "Jackson County, MO",
    carrierLogoColor: "#7D2248",
    carrierLogoTextColor: "#FFFFFF",
  },
  {
    id: "aetna-medicare-3",
    carrier: "Aetna",
    planName: "Aetna Medicare Eagle (HMO)",
    planType: "HMO",
    contractId: "H3312",
    planId: "007",
    starRating: { overall: 4.0, label: "4 out of 5" },
    premium: 0,
    partBPremiumReduction: 30,
    deductible: 0,
    maxOutOfPocket: 4900,
    copays: {
      primaryCare: "$0 copay",
      specialist: "$35 copay",
      urgentCare: "$35 copay",
      emergency: "$90 copay",
      inpatientHospital: "$295/day (Days 1–5)",
      outpatientSurgery: "$175 copay",
    },
    rxDrugs: {
      tier1: "$0 copay",
      tier2: "$5 copay",
      tier3: "$42 copay",
      tier4: "$95 copay",
      deductible: "$0",
      gap: true,
      initialCoverageLimit: "$5,030",
    },
    extraBenefits: {
      dental: { covered: true, details: "Comprehensive dental", annualLimit: "$2,500" },
      vision: { covered: true, details: "Annual exam + $200 eyewear" },
      hearing: { covered: true, details: "$1,500 hearing aid allowance" },
      otc: { covered: true, details: "$100/quarter OTC", annualLimit: "$400/year" },
      fitness: { covered: true, details: "SilverSneakers included" },
      transportation: { covered: true, details: "24 one-way trips/year" },
      telehealth: { covered: true, details: "$0 virtual visits" },
      meals: { covered: false, details: "Not covered" },
    },
    networkSize: 2400,
    isNewPlan: true,
    enrollmentPeriod: "Oct 15 – Dec 7",
    effectiveDate: "Jan 1, 2025",
    serviceArea: "Jackson County, MO",
    carrierLogoColor: "#7D2248",
    carrierLogoTextColor: "#FFFFFF",
  },
  {
    id: "aetna-medicare-4",
    carrier: "Aetna",
    planName: "Aetna Medicare Prime (PPO)",
    planType: "PPO",
    contractId: "H3312",
    planId: "011",
    starRating: { overall: 4.5, label: "4.5 out of 5" },
    premium: 39,
    partBPremiumReduction: 0,
    deductible: 0,
    maxOutOfPocket: 3400,
    copays: {
      primaryCare: "$0 copay",
      specialist: "$25 copay",
      urgentCare: "$25 copay",
      emergency: "$75 copay",
      inpatientHospital: "$200/day (Days 1–5)",
      outpatientSurgery: "$125 copay",
    },
    rxDrugs: {
      tier1: "$0 copay",
      tier2: "$4 copay",
      tier3: "$38 copay",
      tier4: "$85 copay",
      deductible: "$0",
      gap: true,
      initialCoverageLimit: "$5,030",
    },
    extraBenefits: {
      dental: { covered: true, details: "Full dental coverage", annualLimit: "$3,000" },
      vision: { covered: true, details: "Annual exam + $300 eyewear" },
      hearing: { covered: true, details: "$2,000 hearing aid allowance" },
      otc: { covered: true, details: "$150/quarter OTC", annualLimit: "$600/year" },
      fitness: { covered: true, details: "SilverSneakers + gym reimbursement" },
      transportation: { covered: true, details: "36 one-way trips/year" },
      telehealth: { covered: true, details: "$0 virtual visits" },
      meals: { covered: true, details: "28 meals after hospital stay" },
    },
    networkSize: 3200,
    enrollmentPeriod: "Oct 15 – Dec 7",
    effectiveDate: "Jan 1, 2025",
    serviceArea: "Jackson County, MO",
    carrierLogoColor: "#7D2248",
    carrierLogoTextColor: "#FFFFFF",
  },

  // ─── Cigna (4 plans) ──────────────────────────────────────────────────────
  {
    id: "cigna-true-1",
    carrier: "Cigna",
    planName: "Cigna TrueChoice (PPO)",
    planType: "PPO",
    contractId: "H4513",
    planId: "001",
    starRating: { overall: 3.5, label: "3.5 out of 5" },
    premium: 0,
    partBPremiumReduction: 0,
    deductible: 0,
    maxOutOfPocket: 7550,
    copays: {
      primaryCare: "$5 copay",
      specialist: "$45 copay",
      urgentCare: "$45 copay",
      emergency: "$120 copay",
      inpatientHospital: "$400/day (Days 1–5)",
      outpatientSurgery: "$250 copay",
    },
    rxDrugs: {
      tier1: "$2 copay",
      tier2: "$8 copay",
      tier3: "$47 copay",
      tier4: "$100 copay",
      deductible: "$100",
      gap: false,
      initialCoverageLimit: "$5,030",
    },
    extraBenefits: {
      dental: { covered: true, details: "Preventive dental", annualLimit: "$500" },
      vision: { covered: true, details: "Annual exam + $100 eyewear" },
      hearing: { covered: false, details: "Not covered" },
      otc: { covered: false, details: "Not covered" },
      fitness: { covered: true, details: "Tivity Health gym membership" },
      transportation: { covered: false, details: "Not covered" },
      telehealth: { covered: true, details: "$0 virtual visits" },
      meals: { covered: false, details: "Not covered" },
    },
    networkSize: 2100,
    enrollmentPeriod: "Oct 15 – Dec 7",
    effectiveDate: "Jan 1, 2025",
    serviceArea: "Jackson County, MO",
    carrierLogoColor: "#E8002D",
    carrierLogoTextColor: "#FFFFFF",
  },
  {
    id: "cigna-connect-1",
    carrier: "Cigna",
    planName: "Cigna Connect (HMO)",
    planType: "HMO",
    contractId: "H4513",
    planId: "003",
    starRating: { overall: 4.0, label: "4 out of 5" },
    premium: 0,
    partBPremiumReduction: 0,
    deductible: 0,
    maxOutOfPocket: 5500,
    copays: {
      primaryCare: "$0 copay",
      specialist: "$40 copay",
      urgentCare: "$40 copay",
      emergency: "$90 copay",
      inpatientHospital: "$325/day (Days 1–5)",
      outpatientSurgery: "$200 copay",
    },
    rxDrugs: {
      tier1: "$0 copay",
      tier2: "$6 copay",
      tier3: "$44 copay",
      tier4: "$100 copay",
      deductible: "$0",
      gap: false,
      initialCoverageLimit: "$5,030",
    },
    extraBenefits: {
      dental: { covered: true, details: "Preventive + basic dental", annualLimit: "$1,000" },
      vision: { covered: true, details: "Annual exam + $150 eyewear" },
      hearing: { covered: true, details: "$500 hearing aid allowance" },
      otc: { covered: true, details: "$50/quarter OTC", annualLimit: "$200/year" },
      fitness: { covered: true, details: "Tivity Health gym membership" },
      transportation: { covered: false, details: "Not covered" },
      telehealth: { covered: true, details: "$0 virtual visits" },
      meals: { covered: false, details: "Not covered" },
    },
    networkSize: 2600,
    enrollmentPeriod: "Oct 15 – Dec 7",
    effectiveDate: "Jan 1, 2025",
    serviceArea: "Jackson County, MO",
    carrierLogoColor: "#E8002D",
    carrierLogoTextColor: "#FFFFFF",
  },
  {
    id: "cigna-secure-1",
    carrier: "Cigna",
    planName: "Cigna Secure (HMO)",
    planType: "HMO",
    contractId: "H4513",
    planId: "007",
    starRating: { overall: 4.0, label: "4 out of 5" },
    premium: 0,
    partBPremiumReduction: 0,
    deductible: 0,
    maxOutOfPocket: 4900,
    copays: {
      primaryCare: "$0 copay",
      specialist: "$35 copay",
      urgentCare: "$35 copay",
      emergency: "$90 copay",
      inpatientHospital: "$275/day (Days 1–5)",
      outpatientSurgery: "$175 copay",
    },
    rxDrugs: {
      tier1: "$0 copay",
      tier2: "$5 copay",
      tier3: "$42 copay",
      tier4: "$95 copay",
      deductible: "$0",
      gap: true,
      initialCoverageLimit: "$5,030",
    },
    extraBenefits: {
      dental: { covered: true, details: "Comprehensive dental", annualLimit: "$2,000" },
      vision: { covered: true, details: "Annual exam + $200 eyewear" },
      hearing: { covered: true, details: "$1,000 hearing aid allowance" },
      otc: { covered: true, details: "$75/quarter OTC", annualLimit: "$300/year" },
      fitness: { covered: true, details: "Tivity Health gym membership" },
      transportation: { covered: true, details: "12 one-way trips/year" },
      telehealth: { covered: true, details: "$0 virtual visits" },
      meals: { covered: false, details: "Not covered" },
    },
    networkSize: 2600,
    enrollmentPeriod: "Oct 15 – Dec 7",
    effectiveDate: "Jan 1, 2025",
    serviceArea: "Jackson County, MO",
    carrierLogoColor: "#E8002D",
    carrierLogoTextColor: "#FFFFFF",
  },
  {
    id: "cigna-extra-1",
    carrier: "Cigna",
    planName: "Cigna Extra Benefits Plus (PPO)",
    planType: "PPO",
    contractId: "H4513",
    planId: "012",
    starRating: { overall: 3.5, label: "3.5 out of 5" },
    premium: 19,
    partBPremiumReduction: 0,
    deductible: 0,
    maxOutOfPocket: 5500,
    copays: {
      primaryCare: "$0 copay",
      specialist: "$35 copay",
      urgentCare: "$35 copay",
      emergency: "$90 copay",
      inpatientHospital: "$300/day (Days 1–5)",
      outpatientSurgery: "$175 copay",
    },
    rxDrugs: {
      tier1: "$0 copay",
      tier2: "$5 copay",
      tier3: "$42 copay",
      tier4: "$95 copay",
      deductible: "$0",
      gap: true,
      initialCoverageLimit: "$5,030",
    },
    extraBenefits: {
      dental: { covered: true, details: "Comprehensive dental", annualLimit: "$2,500" },
      vision: { covered: true, details: "Annual exam + $250 eyewear" },
      hearing: { covered: true, details: "$1,500 hearing aid allowance" },
      otc: { covered: true, details: "$125/quarter OTC", annualLimit: "$500/year" },
      fitness: { covered: true, details: "Tivity Health gym membership" },
      transportation: { covered: true, details: "24 one-way trips/year" },
      telehealth: { covered: true, details: "$0 virtual visits" },
      meals: { covered: false, details: "Not covered" },
    },
    networkSize: 2100,
    enrollmentPeriod: "Oct 15 – Dec 7",
    effectiveDate: "Jan 1, 2025",
    serviceArea: "Jackson County, MO",
    carrierLogoColor: "#E8002D",
    carrierLogoTextColor: "#FFFFFF",
  },

  // ─── WellCare (4 plans) ───────────────────────────────────────────────────
  {
    id: "wellcare-value-1",
    carrier: "WellCare",
    planName: "WellCare Value Script (HMO)",
    planType: "HMO",
    contractId: "H5427",
    planId: "001",
    starRating: { overall: 3.0, label: "3 out of 5" },
    premium: 0,
    partBPremiumReduction: 0,
    deductible: 0,
    maxOutOfPocket: 7550,
    copays: {
      primaryCare: "$5 copay",
      specialist: "$50 copay",
      urgentCare: "$50 copay",
      emergency: "$120 copay",
      inpatientHospital: "$425/day (Days 1–5)",
      outpatientSurgery: "$275 copay",
    },
    rxDrugs: {
      tier1: "$0 copay",
      tier2: "$5 copay",
      tier3: "$42 copay",
      tier4: "$100 copay",
      deductible: "$0",
      gap: false,
      initialCoverageLimit: "$5,030",
    },
    extraBenefits: {
      dental: { covered: true, details: "Preventive dental", annualLimit: "$500" },
      vision: { covered: true, details: "Annual exam + $75 eyewear" },
      hearing: { covered: false, details: "Not covered" },
      otc: { covered: true, details: "$25/quarter OTC", annualLimit: "$100/year" },
      fitness: { covered: true, details: "Gym membership included" },
      transportation: { covered: false, details: "Not covered" },
      telehealth: { covered: true, details: "$0 virtual visits" },
      meals: { covered: false, details: "Not covered" },
    },
    networkSize: 1800,
    enrollmentPeriod: "Oct 15 – Dec 7",
    effectiveDate: "Jan 1, 2025",
    serviceArea: "Jackson County, MO",
    carrierLogoColor: "#00A651",
    carrierLogoTextColor: "#FFFFFF",
  },
  {
    id: "wellcare-classic-1",
    carrier: "WellCare",
    planName: "WellCare Classic (HMO)",
    planType: "HMO",
    contractId: "H5427",
    planId: "003",
    starRating: { overall: 3.5, label: "3.5 out of 5" },
    premium: 0,
    partBPremiumReduction: 0,
    deductible: 0,
    maxOutOfPocket: 6700,
    copays: {
      primaryCare: "$0 copay",
      specialist: "$45 copay",
      urgentCare: "$45 copay",
      emergency: "$90 copay",
      inpatientHospital: "$375/day (Days 1–5)",
      outpatientSurgery: "$225 copay",
    },
    rxDrugs: {
      tier1: "$1 copay",
      tier2: "$7 copay",
      tier3: "$45 copay",
      tier4: "$100 copay",
      deductible: "$0",
      gap: false,
      initialCoverageLimit: "$5,030",
    },
    extraBenefits: {
      dental: { covered: true, details: "Preventive + basic dental", annualLimit: "$1,000" },
      vision: { covered: true, details: "Annual exam + $100 eyewear" },
      hearing: { covered: false, details: "Not covered" },
      otc: { covered: true, details: "$50/quarter OTC", annualLimit: "$200/year" },
      fitness: { covered: true, details: "Gym membership included" },
      transportation: { covered: false, details: "Not covered" },
      telehealth: { covered: true, details: "$0 virtual visits" },
      meals: { covered: false, details: "Not covered" },
    },
    networkSize: 2000,
    enrollmentPeriod: "Oct 15 – Dec 7",
    effectiveDate: "Jan 1, 2025",
    serviceArea: "Jackson County, MO",
    carrierLogoColor: "#00A651",
    carrierLogoTextColor: "#FFFFFF",
  },
  {
    id: "wellcare-select-1",
    carrier: "WellCare",
    planName: "WellCare Select (PPO)",
    planType: "PPO",
    contractId: "H5427",
    planId: "007",
    starRating: { overall: 3.5, label: "3.5 out of 5" },
    premium: 0,
    partBPremiumReduction: 0,
    deductible: 0,
    maxOutOfPocket: 7550,
    copays: {
      primaryCare: "$5 copay",
      specialist: "$45 copay",
      urgentCare: "$45 copay",
      emergency: "$120 copay",
      inpatientHospital: "$400/day (Days 1–5)",
      outpatientSurgery: "$250 copay",
    },
    rxDrugs: {
      tier1: "$2 copay",
      tier2: "$8 copay",
      tier3: "$47 copay",
      tier4: "$100 copay",
      deductible: "$100",
      gap: false,
      initialCoverageLimit: "$5,030",
    },
    extraBenefits: {
      dental: { covered: true, details: "Preventive dental", annualLimit: "$750" },
      vision: { covered: true, details: "Annual exam + $125 eyewear" },
      hearing: { covered: true, details: "$500 hearing aid allowance" },
      otc: { covered: true, details: "$50/quarter OTC", annualLimit: "$200/year" },
      fitness: { covered: true, details: "Gym membership included" },
      transportation: { covered: false, details: "Not covered" },
      telehealth: { covered: true, details: "$0 virtual visits" },
      meals: { covered: false, details: "Not covered" },
    },
    networkSize: 2200,
    enrollmentPeriod: "Oct 15 – Dec 7",
    effectiveDate: "Jan 1, 2025",
    serviceArea: "Jackson County, MO",
    carrierLogoColor: "#00A651",
    carrierLogoTextColor: "#FFFFFF",
  },
  {
    id: "wellcare-ultra-1",
    carrier: "WellCare",
    planName: "WellCare Ultra (HMO)",
    planType: "HMO",
    contractId: "H5427",
    planId: "011",
    starRating: { overall: 4.0, label: "4 out of 5" },
    premium: 0,
    partBPremiumReduction: 0,
    deductible: 0,
    maxOutOfPocket: 5500,
    copays: {
      primaryCare: "$0 copay",
      specialist: "$40 copay",
      urgentCare: "$40 copay",
      emergency: "$90 copay",
      inpatientHospital: "$325/day (Days 1–5)",
      outpatientSurgery: "$200 copay",
    },
    rxDrugs: {
      tier1: "$0 copay",
      tier2: "$5 copay",
      tier3: "$42 copay",
      tier4: "$95 copay",
      deductible: "$0",
      gap: true,
      initialCoverageLimit: "$5,030",
    },
    extraBenefits: {
      dental: { covered: true, details: "Comprehensive dental", annualLimit: "$2,000" },
      vision: { covered: true, details: "Annual exam + $200 eyewear" },
      hearing: { covered: true, details: "$1,000 hearing aid allowance" },
      otc: { covered: true, details: "$100/quarter OTC", annualLimit: "$400/year" },
      fitness: { covered: true, details: "Gym membership included" },
      transportation: { covered: true, details: "12 one-way trips/year" },
      telehealth: { covered: true, details: "$0 virtual visits" },
      meals: { covered: false, details: "Not covered" },
    },
    networkSize: 2000,
    isNewPlan: true,
    enrollmentPeriod: "Oct 15 – Dec 7",
    effectiveDate: "Jan 1, 2025",
    serviceArea: "Jackson County, MO",
    carrierLogoColor: "#00A651",
    carrierLogoTextColor: "#FFFFFF",
  },

  // ─── Blue KC (4 plans) ────────────────────────────────────────────────────
  {
    id: "bluekc-select-1",
    carrier: "Blue KC",
    planName: "BlueMedicare HMO Select",
    planType: "HMO",
    contractId: "H3655",
    planId: "001",
    starRating: { overall: 4.0, label: "4 out of 5" },
    premium: 0,
    partBPremiumReduction: 0,
    deductible: 0,
    maxOutOfPocket: 5900,
    copays: {
      primaryCare: "$0 copay",
      specialist: "$40 copay",
      urgentCare: "$40 copay",
      emergency: "$120 copay",
      inpatientHospital: "$350/day (Days 1–5)",
      outpatientSurgery: "$200 copay",
    },
    rxDrugs: {
      tier1: "$1 copay",
      tier2: "$6 copay",
      tier3: "$44 copay",
      tier4: "$100 copay",
      deductible: "$0",
      gap: false,
      initialCoverageLimit: "$5,030",
    },
    extraBenefits: {
      dental: { covered: true, details: "Preventive + basic dental", annualLimit: "$1,000" },
      vision: { covered: true, details: "Annual exam + $150 eyewear" },
      hearing: { covered: true, details: "$500 hearing aid allowance" },
      otc: { covered: true, details: "$50/quarter OTC", annualLimit: "$200/year" },
      fitness: { covered: true, details: "Silver&Fit gym membership" },
      transportation: { covered: false, details: "Not covered" },
      telehealth: { covered: true, details: "$0 virtual visits" },
      meals: { covered: false, details: "Not covered" },
    },
    networkSize: 2900,
    enrollmentPeriod: "Oct 15 – Dec 7",
    effectiveDate: "Jan 1, 2025",
    serviceArea: "Jackson County, MO",
    carrierLogoColor: "#003087",
    carrierLogoTextColor: "#FFFFFF",
  },
  {
    id: "bluekc-choice-1",
    carrier: "Blue KC",
    planName: "BlueMedicare PPO Choice",
    planType: "PPO",
    contractId: "H3655",
    planId: "003",
    starRating: { overall: 4.0, label: "4 out of 5" },
    premium: 0,
    partBPremiumReduction: 0,
    deductible: 0,
    maxOutOfPocket: 7550,
    copays: {
      primaryCare: "$5 copay",
      specialist: "$45 copay",
      urgentCare: "$45 copay",
      emergency: "$120 copay",
      inpatientHospital: "$375/day (Days 1–5)",
      outpatientSurgery: "$225 copay",
    },
    rxDrugs: {
      tier1: "$2 copay",
      tier2: "$8 copay",
      tier3: "$47 copay",
      tier4: "$100 copay",
      deductible: "$0",
      gap: false,
      initialCoverageLimit: "$5,030",
    },
    extraBenefits: {
      dental: { covered: true, details: "Preventive dental", annualLimit: "$750" },
      vision: { covered: true, details: "Annual exam + $100 eyewear" },
      hearing: { covered: false, details: "Not covered" },
      otc: { covered: false, details: "Not covered" },
      fitness: { covered: true, details: "Silver&Fit gym membership" },
      transportation: { covered: false, details: "Not covered" },
      telehealth: { covered: true, details: "$0 virtual visits" },
      meals: { covered: false, details: "Not covered" },
    },
    networkSize: 3400,
    enrollmentPeriod: "Oct 15 – Dec 7",
    effectiveDate: "Jan 1, 2025",
    serviceArea: "Jackson County, MO",
    carrierLogoColor: "#003087",
    carrierLogoTextColor: "#FFFFFF",
  },
  {
    id: "bluekc-premier-1",
    carrier: "Blue KC",
    planName: "BlueMedicare HMO Premier",
    planType: "HMO",
    contractId: "H3655",
    planId: "007",
    starRating: { overall: 4.5, label: "4.5 out of 5" },
    premium: 0,
    partBPremiumReduction: 40,
    deductible: 0,
    maxOutOfPocket: 4000,
    copays: {
      primaryCare: "$0 copay",
      specialist: "$30 copay",
      urgentCare: "$30 copay",
      emergency: "$90 copay",
      inpatientHospital: "$250/day (Days 1–5)",
      outpatientSurgery: "$150 copay",
    },
    rxDrugs: {
      tier1: "$0 copay",
      tier2: "$4 copay",
      tier3: "$40 copay",
      tier4: "$90 copay",
      deductible: "$0",
      gap: true,
      initialCoverageLimit: "$5,030",
    },
    extraBenefits: {
      dental: { covered: true, details: "Comprehensive dental", annualLimit: "$3,000" },
      vision: { covered: true, details: "Annual exam + $250 eyewear" },
      hearing: { covered: true, details: "$2,000 hearing aid allowance" },
      otc: { covered: true, details: "$150/quarter OTC", annualLimit: "$600/year" },
      fitness: { covered: true, details: "Silver&Fit gym membership" },
      transportation: { covered: true, details: "24 one-way trips/year" },
      telehealth: { covered: true, details: "$0 virtual visits" },
      meals: { covered: true, details: "28 meals after hospital stay" },
    },
    networkSize: 2900,
    isBestMatch: false,
    isMostPopular: false,
    enrollmentPeriod: "Oct 15 – Dec 7",
    effectiveDate: "Jan 1, 2025",
    serviceArea: "Jackson County, MO",
    carrierLogoColor: "#003087",
    carrierLogoTextColor: "#FFFFFF",
  },
  {
    id: "bluekc-advantage-1",
    carrier: "Blue KC",
    planName: "BlueMedicare PPO Advantage",
    planType: "PPO",
    contractId: "H3655",
    planId: "010",
    starRating: { overall: 4.0, label: "4 out of 5" },
    premium: 59,
    partBPremiumReduction: 0,
    deductible: 0,
    maxOutOfPocket: 2900,
    copays: {
      primaryCare: "$0 copay",
      specialist: "$20 copay",
      urgentCare: "$20 copay",
      emergency: "$65 copay",
      inpatientHospital: "$175/day (Days 1–5)",
      outpatientSurgery: "$100 copay",
    },
    rxDrugs: {
      tier1: "$0 copay",
      tier2: "$3 copay",
      tier3: "$35 copay",
      tier4: "$80 copay",
      deductible: "$0",
      gap: true,
      initialCoverageLimit: "$5,030",
    },
    extraBenefits: {
      dental: { covered: true, details: "Full dental coverage", annualLimit: "$4,000" },
      vision: { covered: true, details: "Annual exam + $350 eyewear" },
      hearing: { covered: true, details: "$3,000 hearing aid allowance" },
      otc: { covered: true, details: "$200/quarter OTC", annualLimit: "$800/year" },
      fitness: { covered: true, details: "Silver&Fit + gym reimbursement" },
      transportation: { covered: true, details: "48 one-way trips/year" },
      telehealth: { covered: true, details: "$0 virtual visits" },
      meals: { covered: true, details: "56 meals after hospital stay" },
    },
    networkSize: 3400,
    enrollmentPeriod: "Oct 15 – Dec 7",
    effectiveDate: "Jan 1, 2025",
    serviceArea: "Jackson County, MO",
    carrierLogoColor: "#003087",
    carrierLogoTextColor: "#FFFFFF",
  },
];


export const POPULAR_RX_DRUGS = [
  // --- Blood Pressure / Heart ---
  { id: "rx-1", name: "Metformin", dosage: "500mg", frequency: "Twice daily", isGeneric: true },
  { id: "rx-2", name: "Lisinopril", dosage: "10mg", frequency: "Once daily", isGeneric: true },
  { id: "rx-3", name: "Atorvastatin", dosage: "20mg", frequency: "Once daily", isGeneric: true },
  { id: "rx-4", name: "Amlodipine", dosage: "5mg", frequency: "Once daily", isGeneric: true },
  { id: "rx-5", name: "Omeprazole", dosage: "20mg", frequency: "Once daily", isGeneric: true },
  { id: "rx-6", name: "Eliquis", dosage: "5mg", frequency: "Twice daily", isGeneric: false },
  { id: "rx-7", name: "Jardiance", dosage: "10mg", frequency: "Once daily", isGeneric: false },
  { id: "rx-8", name: "Xarelto", dosage: "20mg", frequency: "Once daily", isGeneric: false },
  { id: "rx-9", name: "Entresto", dosage: "49/51mg", frequency: "Twice daily", isGeneric: false },
  { id: "rx-10", name: "Ozempic", dosage: "0.5mg", frequency: "Weekly injection", isGeneric: false },
  { id: "rx-11", name: "Losartan", dosage: "50mg", frequency: "Once daily", isGeneric: true },
  { id: "rx-12", name: "Metoprolol Succinate", dosage: "25mg", frequency: "Once daily", isGeneric: true },
  { id: "rx-13", name: "Hydrochlorothiazide", dosage: "25mg", frequency: "Once daily", isGeneric: true },
  { id: "rx-14", name: "Carvedilol", dosage: "12.5mg", frequency: "Twice daily", isGeneric: true },
  { id: "rx-15", name: "Valsartan", dosage: "160mg", frequency: "Once daily", isGeneric: true },
  { id: "rx-16", name: "Warfarin", dosage: "5mg", frequency: "Once daily", isGeneric: true },
  { id: "rx-17", name: "Clopidogrel", dosage: "75mg", frequency: "Once daily", isGeneric: true },
  { id: "rx-18", name: "Diltiazem", dosage: "120mg", frequency: "Once daily", isGeneric: true },
  // --- Diabetes ---
  { id: "rx-19", name: "Glipizide", dosage: "5mg", frequency: "Once daily", isGeneric: true },
  { id: "rx-20", name: "Januvia", dosage: "100mg", frequency: "Once daily", isGeneric: false },
  { id: "rx-21", name: "Trulicity", dosage: "1.5mg", frequency: "Weekly injection", isGeneric: false },
  { id: "rx-22", name: "Farxiga", dosage: "10mg", frequency: "Once daily", isGeneric: false },
  { id: "rx-23", name: "Lantus", dosage: "100 units/mL", frequency: "Once daily", isGeneric: false },
  { id: "rx-24", name: "Humalog", dosage: "100 units/mL", frequency: "With meals", isGeneric: false },
  { id: "rx-25", name: "Rybelsus", dosage: "7mg", frequency: "Once daily", isGeneric: false },
  { id: "rx-26", name: "Mounjaro", dosage: "5mg", frequency: "Weekly injection", isGeneric: false },
  // --- Cholesterol ---
  { id: "rx-27", name: "Rosuvastatin", dosage: "10mg", frequency: "Once daily", isGeneric: true },
  { id: "rx-28", name: "Simvastatin", dosage: "20mg", frequency: "Once daily", isGeneric: true },
  { id: "rx-29", name: "Pravastatin", dosage: "40mg", frequency: "Once daily", isGeneric: true },
  { id: "rx-30", name: "Ezetimibe", dosage: "10mg", frequency: "Once daily", isGeneric: true },
  { id: "rx-31", name: "Repatha", dosage: "140mg", frequency: "Every 2 weeks", isGeneric: false },
  // --- Pain / Inflammation ---
  { id: "rx-32", name: "Gabapentin", dosage: "300mg", frequency: "Three times daily", isGeneric: true },
  { id: "rx-33", name: "Tramadol", dosage: "50mg", frequency: "Every 6 hours as needed", isGeneric: true },
  { id: "rx-34", name: "Meloxicam", dosage: "15mg", frequency: "Once daily", isGeneric: true },
  { id: "rx-35", name: "Pregabalin", dosage: "75mg", frequency: "Twice daily", isGeneric: true },
  { id: "rx-36", name: "Celecoxib", dosage: "200mg", frequency: "Once daily", isGeneric: true },
  { id: "rx-37", name: "Duloxetine", dosage: "60mg", frequency: "Once daily", isGeneric: true },
  // --- Respiratory ---
  { id: "rx-38", name: "Albuterol Inhaler", dosage: "90mcg", frequency: "As needed", isGeneric: true },
  { id: "rx-39", name: "Symbicort", dosage: "160/4.5mcg", frequency: "Twice daily", isGeneric: false },
  { id: "rx-40", name: "Spiriva", dosage: "18mcg", frequency: "Once daily", isGeneric: false },
  { id: "rx-41", name: "Breo Ellipta", dosage: "100/25mcg", frequency: "Once daily", isGeneric: false },
  { id: "rx-42", name: "Trelegy Ellipta", dosage: "100/62.5/25mcg", frequency: "Once daily", isGeneric: false },
  { id: "rx-43", name: "Montelukast", dosage: "10mg", frequency: "Once daily", isGeneric: true },
  // --- Mental Health ---
  { id: "rx-44", name: "Sertraline", dosage: "50mg", frequency: "Once daily", isGeneric: true },
  { id: "rx-45", name: "Escitalopram", dosage: "10mg", frequency: "Once daily", isGeneric: true },
  { id: "rx-46", name: "Trazodone", dosage: "50mg", frequency: "At bedtime", isGeneric: true },
  { id: "rx-47", name: "Buspirone", dosage: "10mg", frequency: "Twice daily", isGeneric: true },
  { id: "rx-48", name: "Mirtazapine", dosage: "15mg", frequency: "At bedtime", isGeneric: true },
  // --- Thyroid ---
  { id: "rx-49", name: "Levothyroxine", dosage: "50mcg", frequency: "Once daily", isGeneric: true },
  { id: "rx-50", name: "Synthroid", dosage: "100mcg", frequency: "Once daily", isGeneric: false },
  // --- Eye Care ---
  { id: "rx-51", name: "Latanoprost", dosage: "0.005%", frequency: "Once daily at bedtime", isGeneric: true },
  { id: "rx-52", name: "Timolol Eye Drops", dosage: "0.5%", frequency: "Twice daily", isGeneric: true },
  // --- GI / Acid Reflux ---
  { id: "rx-53", name: "Pantoprazole", dosage: "40mg", frequency: "Once daily", isGeneric: true },
  { id: "rx-54", name: "Famotidine", dosage: "20mg", frequency: "Twice daily", isGeneric: true },
  { id: "rx-55", name: "Ondansetron", dosage: "4mg", frequency: "As needed", isGeneric: true },
  // --- Bone Health ---
  { id: "rx-56", name: "Alendronate", dosage: "70mg", frequency: "Once weekly", isGeneric: true },
  { id: "rx-57", name: "Prolia", dosage: "60mg", frequency: "Every 6 months", isGeneric: false },
  // --- Blood Thinners / Misc ---
  { id: "rx-58", name: "Furosemide", dosage: "40mg", frequency: "Once daily", isGeneric: true },
  { id: "rx-59", name: "Spironolactone", dosage: "25mg", frequency: "Once daily", isGeneric: true },
  { id: "rx-60", name: "Tamsulosin", dosage: "0.4mg", frequency: "Once daily", isGeneric: true },
  { id: "rx-61", name: "Finasteride", dosage: "5mg", frequency: "Once daily", isGeneric: true },
  { id: "rx-62", name: "Potassium Chloride", dosage: "20mEq", frequency: "Once daily", isGeneric: true },
  { id: "rx-63", name: "Prednisone", dosage: "10mg", frequency: "Once daily", isGeneric: true },
  { id: "rx-64", name: "Allopurinol", dosage: "300mg", frequency: "Once daily", isGeneric: true },
  { id: "rx-65", name: "Colchicine", dosage: "0.6mg", frequency: "Once daily", isGeneric: true },
  // --- Specialty / Brand ---
  { id: "rx-66", name: "Humira", dosage: "40mg", frequency: "Every 2 weeks", isGeneric: false },
  { id: "rx-67", name: "Keytruda", dosage: "200mg", frequency: "Every 3 weeks", isGeneric: false },
  { id: "rx-68", name: "Xeljanz", dosage: "5mg", frequency: "Twice daily", isGeneric: false },
  { id: "rx-69", name: "Rinvoq", dosage: "15mg", frequency: "Once daily", isGeneric: false },
  { id: "rx-70", name: "Stelara", dosage: "45mg", frequency: "Every 12 weeks", isGeneric: false },
];

export const POPULAR_DOCTORS = [
  // --- Primary Care / Internal Medicine ---
  { id: "dr-1", name: "Dr. Sarah Johnson, MD", specialty: "Internal Medicine", npi: "1234567890", address: "4400 Broadway Blvd, Kansas City, MO 64111" },
  { id: "dr-2", name: "Dr. Michael Chen, MD", specialty: "Cardiology", npi: "2345678901", address: "2301 Holmes St, Kansas City, MO 64108" },
  { id: "dr-3", name: "Dr. Patricia Williams, DO", specialty: "Family Medicine", npi: "3456789012", address: "1000 Carondelet Dr, Kansas City, MO 64114" },
  { id: "dr-4", name: "Dr. Robert Martinez, MD", specialty: "Endocrinology", npi: "4567890123", address: "4320 Wornall Rd, Kansas City, MO 64111" },
  { id: "dr-5", name: "Dr. Lisa Thompson, MD", specialty: "Orthopedics", npi: "5678901234", address: "2800 Clay Edwards Dr, Kansas City, MO 64116" },
  { id: "dr-6", name: "Dr. James Wilson, MD", specialty: "Pulmonology", npi: "6789012345", address: "1 Hospital Dr, Kansas City, MO 64108" },
  { id: "dr-7", name: "Dr. Karen Davis, MD", specialty: "Family Medicine", npi: "7890123456", address: "6420 Prospect Ave, Kansas City, MO 64132" },
  { id: "dr-8", name: "Dr. David Lee, MD", specialty: "Internal Medicine", npi: "8901234567", address: "11800 NW Plaza Cir, Kansas City, MO 64153" },
  { id: "dr-9", name: "Dr. Jennifer Garcia, MD", specialty: "Geriatric Medicine", npi: "9012345678", address: "2330 E Meyer Blvd, Kansas City, MO 64132" },
  { id: "dr-10", name: "Dr. William Brown, DO", specialty: "Family Medicine", npi: "1023456789", address: "7900 Lee's Summit Rd, Kansas City, MO 64139" },
  // --- Cardiology ---
  { id: "dr-11", name: "Dr. Amanda Foster, MD", specialty: "Cardiology", npi: "1123456780", address: "4330 Wornall Rd, Kansas City, MO 64111" },
  { id: "dr-12", name: "Dr. Richard Kim, MD", specialty: "Cardiology", npi: "1223456780", address: "2316 E Meyer Blvd, Kansas City, MO 64132" },
  { id: "dr-13", name: "Dr. Thomas Wright, MD", specialty: "Interventional Cardiology", npi: "1323456780", address: "6400 Prospect Ave, Kansas City, MO 64132" },
  // --- Endocrinology / Diabetes ---
  { id: "dr-14", name: "Dr. Michelle Patel, MD", specialty: "Endocrinology", npi: "1423456780", address: "2301 Holmes St, Suite 300, Kansas City, MO 64108" },
  { id: "dr-15", name: "Dr. Steven Clark, MD", specialty: "Endocrinology", npi: "1523456780", address: "4400 Broadway, Suite 401, Kansas City, MO 64111" },
  // --- Orthopedics ---
  { id: "dr-16", name: "Dr. Christopher Hall, MD", specialty: "Orthopedic Surgery", npi: "1623456780", address: "3651 College Blvd, Leawood, KS 66211" },
  { id: "dr-17", name: "Dr. Elizabeth Moore, MD", specialty: "Rheumatology", npi: "1723456780", address: "4320 Wornall Rd, Suite 500, Kansas City, MO 64111" },
  // --- Pulmonology ---
  { id: "dr-18", name: "Dr. Daniel Adams, MD", specialty: "Pulmonology", npi: "1823456780", address: "2300 Holmes St, Kansas City, MO 64108" },
  { id: "dr-19", name: "Dr. Rachel Turner, MD", specialty: "Pulmonology", npi: "1923456780", address: "2800 Clay Edwards Dr, Suite 200, Kansas City, MO 64116" },
  // --- Neurology ---
  { id: "dr-20", name: "Dr. Andrew Phillips, MD", specialty: "Neurology", npi: "2023456780", address: "4400 Broadway Blvd, Suite 500, Kansas City, MO 64111" },
  { id: "dr-21", name: "Dr. Laura Mitchell, MD", specialty: "Neurology", npi: "2123456780", address: "2316 E Meyer Blvd, Suite 100, Kansas City, MO 64132" },
  // --- Gastroenterology ---
  { id: "dr-22", name: "Dr. Jeffrey Roberts, MD", specialty: "Gastroenterology", npi: "2223456780", address: "4320 Wornall Rd, Suite 600, Kansas City, MO 64111" },
  { id: "dr-23", name: "Dr. Susan Baker, MD", specialty: "Gastroenterology", npi: "2323456780", address: "2330 E Meyer Blvd, Suite 200, Kansas City, MO 64132" },
  // --- Ophthalmology ---
  { id: "dr-24", name: "Dr. Mark Campbell, MD", specialty: "Ophthalmology", npi: "2423456780", address: "3901 Rainbow Blvd, Kansas City, KS 66103" },
  { id: "dr-25", name: "Dr. Nancy Evans, MD", specialty: "Ophthalmology", npi: "2523456780", address: "11800 NW Plaza Cir, Suite 300, Kansas City, MO 64153" },
  // --- Dermatology ---
  { id: "dr-26", name: "Dr. Brian Scott, MD", specialty: "Dermatology", npi: "2623456780", address: "4550 Broadway, Kansas City, MO 64111" },
  // --- Urology ---
  { id: "dr-27", name: "Dr. Gregory Nelson, MD", specialty: "Urology", npi: "2723456780", address: "2300 Holmes St, Suite 400, Kansas City, MO 64108" },
  // --- Oncology ---
  { id: "dr-28", name: "Dr. Catherine Young, MD", specialty: "Oncology", npi: "2823456780", address: "2330 E Meyer Blvd, Suite 300, Kansas City, MO 64132" },
  { id: "dr-29", name: "Dr. Paul Hernandez, MD", specialty: "Oncology", npi: "2923456780", address: "4400 Broadway Blvd, Suite 700, Kansas City, MO 64111" },
  // --- Psychiatry ---
  { id: "dr-30", name: "Dr. Angela King, MD", specialty: "Psychiatry", npi: "3023456780", address: "6420 Prospect Ave, Suite 200, Kansas City, MO 64132" },
  // --- ENT ---
  { id: "dr-31", name: "Dr. Kevin White, MD", specialty: "Otolaryngology (ENT)", npi: "3123456780", address: "3901 Rainbow Blvd, Suite 200, Kansas City, KS 66103" },
  // --- Nephrology ---
  { id: "dr-32", name: "Dr. Diane Lewis, MD", specialty: "Nephrology", npi: "3223456780", address: "2301 Holmes St, Suite 500, Kansas City, MO 64108" },
  // --- Pain Management ---
  { id: "dr-33", name: "Dr. Jason Walker, MD", specialty: "Pain Management", npi: "3323456780", address: "7900 Lee's Summit Rd, Suite 100, Kansas City, MO 64139" },
  // --- Podiatry ---
  { id: "dr-34", name: "Dr. Maria Robinson, DPM", specialty: "Podiatry", npi: "3423456780", address: "11800 NW Plaza Cir, Suite 400, Kansas City, MO 64153" },
  // --- Dentistry ---
  { id: "dr-35", name: "Dr. Ryan Harris, DDS", specialty: "General Dentistry", npi: "3523456780", address: "4550 Broadway, Suite 200, Kansas City, MO 64111" },
];
