// Medicare Advantage Plan Quote Engine — Mock Data
// 24 MA Plans for Jackson County, MO (ZIP 64106)
// Carriers: UHC, Humana, Aetna, Cigna, WellCare, Blue KC

import type { MedicarePlan, Carrier } from "./types";

export const CARRIER_COLORS: Record<Carrier, { bg: string; text: string; border: string }> = {
  UnitedHealthcare: { bg: "#002677", text: "#FFFFFF", border: "#002677" },
  Humana: { bg: "#006D9D", text: "#FFFFFF", border: "#006D9D" },
  Aetna: { bg: "#7D2248", text: "#FFFFFF", border: "#7D2248" },
  Cigna: { bg: "#E8002D", text: "#FFFFFF", border: "#E8002D" },
  WellCare: { bg: "#00A651", text: "#FFFFFF", border: "#00A651" },
  "Blue KC": { bg: "#003087", text: "#FFFFFF", border: "#003087" },
};

export const MOCK_PLANS: MedicarePlan[] = [
  // ─── UnitedHealthcare (4 plans) ───────────────────────────────────────────
  {
    id: "uhc-aarp-1",
    carrier: "UnitedHealthcare",
    planName: "AARP MedicareComplete Choice Plan 1 (PPO)",
    planType: "PPO",
    contractId: "H0609",
    planId: "001",
    starRating: { overall: 4.5, label: "4.5 out of 5" },
    premium: 0,
    partBPremiumReduction: 0,
    deductible: 0,
    maxOutOfPocket: 6700,
    copays: {
      primaryCare: "$0 copay",
      specialist: "$40 copay",
      urgentCare: "$40 copay",
      emergency: "$120 copay",
      inpatientHospital: "$325/day (Days 1–5)",
      outpatientSurgery: "$250 copay",
    },
    rxDrugs: {
      tier1: "$0 copay",
      tier2: "$10 copay",
      tier3: "$47 copay",
      tier4: "$100 copay",
      deductible: "$0",
      gap: true,
      initialCoverageLimit: "$5,030",
    },
    extraBenefits: {
      dental: { covered: true, details: "Comprehensive dental: cleanings, X-rays, fillings, crowns", annualLimit: "$2,000" },
      vision: { covered: true, details: "Annual eye exam + $200 eyewear allowance" },
      hearing: { covered: true, details: "$1,500 hearing aid allowance every 3 years" },
      otc: { covered: true, details: "$100/quarter OTC benefit card", annualLimit: "$400/year" },
      fitness: { covered: true, details: "Renew Active gym membership included" },
      transportation: { covered: true, details: "24 one-way trips/year to medical appointments" },
      telehealth: { covered: true, details: "$0 virtual visits 24/7" },
      meals: { covered: false, details: "Not covered" },
    },
    networkSize: 4200,
    isBestMatch: true,
    isMostPopular: true,
    enrollmentPeriod: "Oct 15 – Dec 7",
    effectiveDate: "Jan 1, 2025",
    serviceArea: "Jackson County, MO",
    carrierLogoColor: "#002677",
    carrierLogoTextColor: "#FFFFFF",
  },
  {
    id: "uhc-aarp-2",
    carrier: "UnitedHealthcare",
    planName: "AARP MedicareComplete Patriot (HMO)",
    planType: "HMO",
    contractId: "H0609",
    planId: "003",
    starRating: { overall: 4.5, label: "4.5 out of 5" },
    premium: 0,
    partBPremiumReduction: 0,
    deductible: 0,
    maxOutOfPocket: 4900,
    copays: {
      primaryCare: "$0 copay",
      specialist: "$35 copay",
      urgentCare: "$35 copay",
      emergency: "$90 copay",
      inpatientHospital: "$275/day (Days 1–5)",
      outpatientSurgery: "$175 copay",
    },
    rxDrugs: {
      tier1: "$0 copay",
      tier2: "$5 copay",
      tier3: "$42 copay",
      tier4: "$95 copay",
      deductible: "$0",
      gap: true,
      initialCoverageLimit: "$5,030",
    },
    extraBenefits: {
      dental: { covered: true, details: "Preventive dental + $1,500 comprehensive", annualLimit: "$1,500" },
      vision: { covered: true, details: "Annual eye exam + $150 eyewear allowance" },
      hearing: { covered: true, details: "$1,000 hearing aid allowance every 3 years" },
      otc: { covered: true, details: "$75/quarter OTC benefit card", annualLimit: "$300/year" },
      fitness: { covered: true, details: "Renew Active gym membership included" },
      transportation: { covered: true, details: "12 one-way trips/year" },
      telehealth: { covered: true, details: "$0 virtual visits 24/7" },
      meals: { covered: false, details: "Not covered" },
    },
    networkSize: 3100,
    isMostPopular: false,
    enrollmentPeriod: "Oct 15 – Dec 7",
    effectiveDate: "Jan 1, 2025",
    serviceArea: "Jackson County, MO",
    carrierLogoColor: "#002677",
    carrierLogoTextColor: "#FFFFFF",
  },
  {
    id: "uhc-aarp-3",
    carrier: "UnitedHealthcare",
    planName: "AARP MedicareComplete Choice Plan 2 (PPO)",
    planType: "PPO",
    contractId: "H0609",
    planId: "005",
    starRating: { overall: 4.0, label: "4 out of 5" },
    premium: 29,
    partBPremiumReduction: 0,
    deductible: 0,
    maxOutOfPocket: 4000,
    copays: {
      primaryCare: "$0 copay",
      specialist: "$30 copay",
      urgentCare: "$30 copay",
      emergency: "$90 copay",
      inpatientHospital: "$250/day (Days 1–5)",
      outpatientSurgery: "$150 copay",
    },
    rxDrugs: {
      tier1: "$0 copay",
      tier2: "$5 copay",
      tier3: "$40 copay",
      tier4: "$90 copay",
      deductible: "$0",
      gap: true,
      initialCoverageLimit: "$5,030",
    },
    extraBenefits: {
      dental: { covered: true, details: "Comprehensive dental coverage", annualLimit: "$3,000" },
      vision: { covered: true, details: "Annual exam + $250 eyewear allowance" },
      hearing: { covered: true, details: "$2,000 hearing aid allowance" },
      otc: { covered: true, details: "$150/quarter OTC benefit card", annualLimit: "$600/year" },
      fitness: { covered: true, details: "Renew Active gym membership" },
      transportation: { covered: true, details: "36 one-way trips/year" },
      telehealth: { covered: true, details: "$0 virtual visits" },
      meals: { covered: true, details: "28 meals after hospital stay" },
    },
    networkSize: 4200,
    enrollmentPeriod: "Oct 15 – Dec 7",
    effectiveDate: "Jan 1, 2025",
    serviceArea: "Jackson County, MO",
    carrierLogoColor: "#002677",
    carrierLogoTextColor: "#FFFFFF",
  },
  {
    id: "uhc-dual-1",
    carrier: "UnitedHealthcare",
    planName: "Dual Complete Plan (HMO-SNP)",
    planType: "SNP",
    contractId: "H0609",
    planId: "010",
    starRating: { overall: 4.0, label: "4 out of 5" },
    premium: 0,
    partBPremiumReduction: 0,
    deductible: 0,
    maxOutOfPocket: 3450,
    copays: {
      primaryCare: "$0 copay",
      specialist: "$0 copay",
      urgentCare: "$0 copay",
      emergency: "$0 copay",
      inpatientHospital: "$0/day",
      outpatientSurgery: "$0 copay",
    },
    rxDrugs: {
      tier1: "$0 copay",
      tier2: "$0 copay",
      tier3: "$0 copay",
      tier4: "$0 copay",
      deductible: "$0",
      gap: true,
      initialCoverageLimit: "$5,030",
    },
    extraBenefits: {
      dental: { covered: true, details: "Full dental coverage", annualLimit: "Unlimited" },
      vision: { covered: true, details: "Full vision coverage" },
      hearing: { covered: true, details: "Full hearing coverage" },
      otc: { covered: true, details: "$125/month OTC benefit", annualLimit: "$1,500/year" },
      fitness: { covered: true, details: "Gym membership included" },
      transportation: { covered: true, details: "Unlimited trips to medical appointments" },
      telehealth: { covered: true, details: "$0 virtual visits" },
      meals: { covered: true, details: "Meals after hospital stay" },
    },
    networkSize: 3100,
    snpType: "Dual Eligible (D-SNP)",
    enrollmentPeriod: "Year-round",
    effectiveDate: "Jan 1, 2025",
    serviceArea: "Jackson County, MO",
    carrierLogoColor: "#002677",
    carrierLogoTextColor: "#FFFFFF",
  },

  // ─── Humana (4 plans) ─────────────────────────────────────────────────────
  {
    id: "humana-gold-1",
    carrier: "Humana",
    planName: "Humana Gold Plus H5619 (HMO)",
    planType: "HMO",
    contractId: "H5619",
    planId: "001",
    starRating: { overall: 4.0, label: "4 out of 5" },
    premium: 0,
    partBPremiumReduction: 0,
    deductible: 0,
    maxOutOfPocket: 5900,
    copays: {
      primaryCare: "$0 copay",
      specialist: "$40 copay",
      urgentCare: "$40 copay",
      emergency: "$120 copay",
      inpatientHospital: "$350/day (Days 1–5)",
      outpatientSurgery: "$200 copay",
    },
    rxDrugs: {
      tier1: "$1 copay",
      tier2: "$6 copay",
      tier3: "$44 copay",
      tier4: "$100 copay",
      deductible: "$0",
      gap: false,
      initialCoverageLimit: "$5,030",
    },
    extraBenefits: {
      dental: { covered: true, details: "Preventive dental + $1,000 comprehensive", annualLimit: "$1,000" },
      vision: { covered: true, details: "Annual exam + $100 eyewear allowance" },
      hearing: { covered: true, details: "$500 hearing aid allowance" },
      otc: { covered: true, details: "$50/quarter OTC benefit", annualLimit: "$200/year" },
      fitness: { covered: true, details: "SilverSneakers gym membership" },
      transportation: { covered: false, details: "Not covered" },
      telehealth: { covered: true, details: "$0 virtual visits" },
      meals: { covered: false, details: "Not covered" },
    },
    networkSize: 2800,
    isMostPopular: true,
    enrollmentPeriod: "Oct 15 – Dec 7",
    effectiveDate: "Jan 1, 2025",
    serviceArea: "Jackson County, MO",
    carrierLogoColor: "#006D9D",
    carrierLogoTextColor: "#FFFFFF",
  },
  {
    id: "humana-choice-1",
    carrier: "Humana",
    planName: "Humana Choice H5216 (PPO)",
    planType: "PPO",
    contractId: "H5216",
    planId: "002",
    starRating: { overall: 3.5, label: "3.5 out of 5" },
    premium: 0,
    partBPremiumReduction: 0,
    deductible: 0,
    maxOutOfPocket: 7550,
    copays: {
      primaryCare: "$5 copay",
      specialist: "$45 copay",
      urgentCare: "$45 copay",
      emergency: "$120 copay",
      inpatientHospital: "$375/day (Days 1–5)",
      outpatientSurgery: "$225 copay",
    },
    rxDrugs: {
      tier1: "$2 copay",
      tier2: "$8 copay",
      tier3: "$47 copay",
      tier4: "$100 copay",
      deductible: "$100",
      gap: false,
      initialCoverageLimit: "$5,030",
    },
    extraBenefits: {
      dental: { covered: true, details: "Preventive dental only", annualLimit: "$500" },
      vision: { covered: true, details: "Annual exam + $75 eyewear allowance" },
      hearing: { covered: false, details: "Not covered" },
      otc: { covered: false, details: "Not covered" },
      fitness: { covered: true, details: "SilverSneakers gym membership" },
      transportation: { covered: false, details: "Not covered" },
      telehealth: { covered: true, details: "$0 virtual visits" },
      meals: { covered: false, details: "Not covered" },
    },
    networkSize: 3500,
    enrollmentPeriod: "Oct 15 – Dec 7",
    effectiveDate: "Jan 1, 2025",
    serviceArea: "Jackson County, MO",
    carrierLogoColor: "#006D9D",
    carrierLogoTextColor: "#FFFFFF",
  },
  {
    id: "humana-value-1",
    carrier: "Humana",
    planName: "Humana Value Plus (HMO)",
    planType: "HMO",
    contractId: "H5619",
    planId: "015",
    starRating: { overall: 4.0, label: "4 out of 5" },
    premium: 0,
    partBPremiumReduction: 20,
    deductible: 0,
    maxOutOfPocket: 4900,
    copays: {
      primaryCare: "$0 copay",
      specialist: "$35 copay",
      urgentCare: "$35 copay",
      emergency: "$90 copay",
      inpatientHospital: "$295/day (Days 1–5)",
      outpatientSurgery: "$175 copay",
    },
    rxDrugs: {
      tier1: "$0 copay",
      tier2: "$5 copay",
      tier3: "$42 copay",
      tier4: "$95 copay",
      deductible: "$0",
      gap: true,
      initialCoverageLimit: "$5,030",
    },
    extraBenefits: {
      dental: { covered: true, details: "Comprehensive dental", annualLimit: "$2,000" },
      vision: { covered: true, details: "Annual exam + $200 eyewear" },
      hearing: { covered: true, details: "$1,000 hearing aid allowance" },
      otc: { covered: true, details: "$100/quarter OTC", annualLimit: "$400/year" },
      fitness: { covered: true, details: "SilverSneakers included" },
      transportation: { covered: true, details: "12 one-way trips/year" },
      telehealth: { covered: true, details: "$0 virtual visits" },
      meals: { covered: false, details: "Not covered" },
    },
    networkSize: 2800,
    isNewPlan: true,
    enrollmentPeriod: "Oct 15 – Dec 7",
    effectiveDate: "Jan 1, 2025",
    serviceArea: "Jackson County, MO",
    carrierLogoColor: "#006D9D",
    carrierLogoTextColor: "#FFFFFF",
  },
  {
    id: "humana-premier-1",
    carrier: "Humana",
    planName: "Humana Premier Rx Plan (PPO)",
    planType: "PPO",
    contractId: "H5216",
    planId: "020",
    starRating: { overall: 4.5, label: "4.5 out of 5" },
    premium: 49,
    partBPremiumReduction: 0,
    deductible: 0,
    maxOutOfPocket: 3400,
    copays: {
      primaryCare: "$0 copay",
      specialist: "$25 copay",
      urgentCare: "$25 copay",
      emergency: "$75 copay",
      inpatientHospital: "$200/day (Days 1–5)",
      outpatientSurgery: "$125 copay",
    },
    rxDrugs: {
      tier1: "$0 copay",
      tier2: "$4 copay",
      tier3: "$38 copay",
      tier4: "$85 copay",
      deductible: "$0",
      gap: true,
      initialCoverageLimit: "$5,030",
    },
    extraBenefits: {
      dental: { covered: true, details: "Full dental coverage", annualLimit: "$3,500" },
      vision: { covered: true, details: "Annual exam + $300 eyewear" },
      hearing: { covered: true, details: "$2,500 hearing aid allowance" },
      otc: { covered: true, details: "$200/quarter OTC", annualLimit: "$800/year" },
      fitness: { covered: true, details: "SilverSneakers + gym reimbursement" },
      transportation: { covered: true, details: "48 one-way trips/year" },
      telehealth: { covered: true, details: "$0 virtual visits" },
      meals: { covered: true, details: "56 meals after hospital stay" },
    },
    networkSize: 3500,
    isBestMatch: false,
    enrollmentPeriod: "Oct 15 – Dec 7",
    effectiveDate: "Jan 1, 2025",
    serviceArea: "Jackson County, MO",
    carrierLogoColor: "#006D9D",
    carrierLogoTextColor: "#FFFFFF",
  },

  // ─── Aetna (4 plans) ──────────────────────────────────────────────────────
  {
    id: "aetna-medicare-1",
    carrier: "Aetna",
    planName: "Aetna Medicare Advantage Value Plan (HMO)",
    planType: "HMO",
    contractId: "H3312",
    planId: "001",
    starRating: { overall: 3.5, label: "3.5 out of 5" },
    premium: 0,
    partBPremiumReduction: 0,
    deductible: 0,
    maxOutOfPocket: 6700,
    copays: {
      primaryCare: "$5 copay",
      specialist: "$45 copay",
      urgentCare: "$45 copay",
      emergency: "$120 copay",
      inpatientHospital: "$400/day (Days 1–5)",
      outpatientSurgery: "$250 copay",
    },
    rxDrugs: {
      tier1: "$2 copay",
      tier2: "$8 copay",
      tier3: "$47 copay",
      tier4: "$100 copay",
      deductible: "$100",
      gap: false,
      initialCoverageLimit: "$5,030",
    },
    extraBenefits: {
      dental: { covered: true, details: "Preventive dental", annualLimit: "$500" },
      vision: { covered: true, details: "Annual exam + $100 eyewear" },
      hearing: { covered: false, details: "Not covered" },
      otc: { covered: true, details: "$25/quarter OTC", annualLimit: "$100/year" },
      fitness: { covered: true, details: "SilverSneakers gym membership" },
      transportation: { covered: false, details: "Not covered" },
      telehealth: { covered: true, details: "$0 virtual visits" },
      meals: { covered: false, details: "Not covered" },
    },
    networkSize: 2400,
    enrollmentPeriod: "Oct 15 – Dec 7",
    effectiveDate: "Jan 1, 2025",
    serviceArea: "Jackson County, MO",
    carrierLogoColor: "#7D2248",
    carrierLogoTextColor: "#FFFFFF",
  },
  {
    id: "aetna-medicare-2",
    carrier: "Aetna",
    planName: "Aetna Medicare Advantage Choice Plan (PPO)",
    planType: "PPO",
    contractId: "H3312",
    planId: "003",
    starRating: { overall: 4.0, label: "4 out of 5" },
    premium: 0,
    partBPremiumReduction: 0,
    deductible: 0,
    maxOutOfPocket: 7550,
    copays: {
      primaryCare: "$0 copay",
      specialist: "$40 copay",
      urgentCare: "$40 copay",
      emergency: "$120 copay",
      inpatientHospital: "$350/day (Days 1–5)",
      outpatientSurgery: "$200 copay",
    },
    rxDrugs: {
      tier1: "$0 copay",
      tier2: "$6 copay",
      tier3: "$44 copay",
      tier4: "$100 copay",
      deductible: "$0",
      gap: false,
      initialCoverageLimit: "$5,030",
    },
    extraBenefits: {
      dental: { covered: true, details: "Preventive + basic dental", annualLimit: "$1,000" },
      vision: { covered: true, details: "Annual exam + $150 eyewear" },
      hearing: { covered: true, details: "$500 hearing aid allowance" },
      otc: { covered: true, details: "$50/quarter OTC", annualLimit: "$200/year" },
      fitness: { covered: true, details: "SilverSneakers included" },
      transportation: { covered: false, details: "Not covered" },
      telehealth: { covered: true, details: "$0 virtual visits" },
      meals: { covered: false, details: "Not covered" },
    },
    networkSize: 3200,
    enrollmentPeriod: "Oct 15 – Dec 7",
    effectiveDate: "Jan 1, 2025",
    serviceArea: "Jackson County, MO",
    carrierLogoColor: "#7D2248",
    carrierLogoTextColor: "#FFFFFF",
  },
  {
    id: "aetna-medicare-3",
    carrier: "Aetna",
    planName: "Aetna Medicare Eagle (HMO)",
    planType: "HMO",
    contractId: "H3312",
    planId: "007",
    starRating: { overall: 4.0, label: "4 out of 5" },
    premium: 0,
    partBPremiumReduction: 30,
    deductible: 0,
    maxOutOfPocket: 4900,
    copays: {
      primaryCare: "$0 copay",
      specialist: "$35 copay",
      urgentCare: "$35 copay",
      emergency: "$90 copay",
      inpatientHospital: "$295/day (Days 1–5)",
      outpatientSurgery: "$175 copay",
    },
    rxDrugs: {
      tier1: "$0 copay",
      tier2: "$5 copay",
      tier3: "$42 copay",
      tier4: "$95 copay",
      deductible: "$0",
      gap: true,
      initialCoverageLimit: "$5,030",
    },
    extraBenefits: {
      dental: { covered: true, details: "Comprehensive dental", annualLimit: "$2,500" },
      vision: { covered: true, details: "Annual exam + $200 eyewear" },
      hearing: { covered: true, details: "$1,500 hearing aid allowance" },
      otc: { covered: true, details: "$100/quarter OTC", annualLimit: "$400/year" },
      fitness: { covered: true, details: "SilverSneakers included" },
      transportation: { covered: true, details: "24 one-way trips/year" },
      telehealth: { covered: true, details: "$0 virtual visits" },
      meals: { covered: false, details: "Not covered" },
    },
    networkSize: 2400,
    isNewPlan: true,
    enrollmentPeriod: "Oct 15 – Dec 7",
    effectiveDate: "Jan 1, 2025",
    serviceArea: "Jackson County, MO",
    carrierLogoColor: "#7D2248",
    carrierLogoTextColor: "#FFFFFF",
  },
  {
    id: "aetna-medicare-4",
    carrier: "Aetna",
    planName: "Aetna Medicare Prime (PPO)",
    planType: "PPO",
    contractId: "H3312",
    planId: "011",
    starRating: { overall: 4.5, label: "4.5 out of 5" },
    premium: 39,
    partBPremiumReduction: 0,
    deductible: 0,
    maxOutOfPocket: 3400,
    copays: {
      primaryCare: "$0 copay",
      specialist: "$25 copay",
      urgentCare: "$25 copay",
      emergency: "$75 copay",
      inpatientHospital: "$200/day (Days 1–5)",
      outpatientSurgery: "$125 copay",
    },
    rxDrugs: {
      tier1: "$0 copay",
      tier2: "$4 copay",
      tier3: "$38 copay",
      tier4: "$85 copay",
      deductible: "$0",
      gap: true,
      initialCoverageLimit: "$5,030",
    },
    extraBenefits: {
      dental: { covered: true, details: "Full dental coverage", annualLimit: "$3,000" },
      vision: { covered: true, details: "Annual exam + $300 eyewear" },
      hearing: { covered: true, details: "$2,000 hearing aid allowance" },
      otc: { covered: true, details: "$150/quarter OTC", annualLimit: "$600/year" },
      fitness: { covered: true, details: "SilverSneakers + gym reimbursement" },
      transportation: { covered: true, details: "36 one-way trips/year" },
      telehealth: { covered: true, details: "$0 virtual visits" },
      meals: { covered: true, details: "28 meals after hospital stay" },
    },
    networkSize: 3200,
    enrollmentPeriod: "Oct 15 – Dec 7",
    effectiveDate: "Jan 1, 2025",
    serviceArea: "Jackson County, MO",
    carrierLogoColor: "#7D2248",
    carrierLogoTextColor: "#FFFFFF",
  },

  // ─── Cigna (4 plans) ──────────────────────────────────────────────────────
  {
    id: "cigna-true-1",
    carrier: "Cigna",
    planName: "Cigna TrueChoice (PPO)",
    planType: "PPO",
    contractId: "H4513",
    planId: "001",
    starRating: { overall: 3.5, label: "3.5 out of 5" },
    premium: 0,
    partBPremiumReduction: 0,
    deductible: 0,
    maxOutOfPocket: 7550,
    copays: {
      primaryCare: "$5 copay",
      specialist: "$45 copay",
      urgentCare: "$45 copay",
      emergency: "$120 copay",
      inpatientHospital: "$400/day (Days 1–5)",
      outpatientSurgery: "$250 copay",
    },
    rxDrugs: {
      tier1: "$2 copay",
      tier2: "$8 copay",
      tier3: "$47 copay",
      tier4: "$100 copay",
      deductible: "$100",
      gap: false,
      initialCoverageLimit: "$5,030",
    },
    extraBenefits: {
      dental: { covered: true, details: "Preventive dental", annualLimit: "$500" },
      vision: { covered: true, details: "Annual exam + $100 eyewear" },
      hearing: { covered: false, details: "Not covered" },
      otc: { covered: false, details: "Not covered" },
      fitness: { covered: true, details: "Tivity Health gym membership" },
      transportation: { covered: false, details: "Not covered" },
      telehealth: { covered: true, details: "$0 virtual visits" },
      meals: { covered: false, details: "Not covered" },
    },
    networkSize: 2100,
    enrollmentPeriod: "Oct 15 – Dec 7",
    effectiveDate: "Jan 1, 2025",
    serviceArea: "Jackson County, MO",
    carrierLogoColor: "#E8002D",
    carrierLogoTextColor: "#FFFFFF",
  },
  {
    id: "cigna-connect-1",
    carrier: "Cigna",
    planName: "Cigna Connect (HMO)",
    planType: "HMO",
    contractId: "H4513",
    planId: "003",
    starRating: { overall: 4.0, label: "4 out of 5" },
    premium: 0,
    partBPremiumReduction: 0,
    deductible: 0,
    maxOutOfPocket: 5500,
    copays: {
      primaryCare: "$0 copay",
      specialist: "$40 copay",
      urgentCare: "$40 copay",
      emergency: "$90 copay",
      inpatientHospital: "$325/day (Days 1–5)",
      outpatientSurgery: "$200 copay",
    },
    rxDrugs: {
      tier1: "$0 copay",
      tier2: "$6 copay",
      tier3: "$44 copay",
      tier4: "$100 copay",
      deductible: "$0",
      gap: false,
      initialCoverageLimit: "$5,030",
    },
    extraBenefits: {
      dental: { covered: true, details: "Preventive + basic dental", annualLimit: "$1,000" },
      vision: { covered: true, details: "Annual exam + $150 eyewear" },
      hearing: { covered: true, details: "$500 hearing aid allowance" },
      otc: { covered: true, details: "$50/quarter OTC", annualLimit: "$200/year" },
      fitness: { covered: true, details: "Tivity Health gym membership" },
      transportation: { covered: false, details: "Not covered" },
      telehealth: { covered: true, details: "$0 virtual visits" },
      meals: { covered: false, details: "Not covered" },
    },
    networkSize: 2600,
    enrollmentPeriod: "Oct 15 – Dec 7",
    effectiveDate: "Jan 1, 2025",
    serviceArea: "Jackson County, MO",
    carrierLogoColor: "#E8002D",
    carrierLogoTextColor: "#FFFFFF",
  },
  {
    id: "cigna-secure-1",
    carrier: "Cigna",
    planName: "Cigna Secure (HMO)",
    planType: "HMO",
    contractId: "H4513",
    planId: "007",
    starRating: { overall: 4.0, label: "4 out of 5" },
    premium: 0,
    partBPremiumReduction: 0,
    deductible: 0,
    maxOutOfPocket: 4900,
    copays: {
      primaryCare: "$0 copay",
      specialist: "$35 copay",
      urgentCare: "$35 copay",
      emergency: "$90 copay",
      inpatientHospital: "$275/day (Days 1–5)",
      outpatientSurgery: "$175 copay",
    },
    rxDrugs: {
      tier1: "$0 copay",
      tier2: "$5 copay",
      tier3: "$42 copay",
      tier4: "$95 copay",
      deductible: "$0",
      gap: true,
      initialCoverageLimit: "$5,030",
    },
    extraBenefits: {
      dental: { covered: true, details: "Comprehensive dental", annualLimit: "$2,000" },
      vision: { covered: true, details: "Annual exam + $200 eyewear" },
      hearing: { covered: true, details: "$1,000 hearing aid allowance" },
      otc: { covered: true, details: "$75/quarter OTC", annualLimit: "$300/year" },
      fitness: { covered: true, details: "Tivity Health gym membership" },
      transportation: { covered: true, details: "12 one-way trips/year" },
      telehealth: { covered: true, details: "$0 virtual visits" },
      meals: { covered: false, details: "Not covered" },
    },
    networkSize: 2600,
    enrollmentPeriod: "Oct 15 – Dec 7",
    effectiveDate: "Jan 1, 2025",
    serviceArea: "Jackson County, MO",
    carrierLogoColor: "#E8002D",
    carrierLogoTextColor: "#FFFFFF",
  },
  {
    id: "cigna-extra-1",
    carrier: "Cigna",
    planName: "Cigna Extra Benefits Plus (PPO)",
    planType: "PPO",
    contractId: "H4513",
    planId: "012",
    starRating: { overall: 3.5, label: "3.5 out of 5" },
    premium: 19,
    partBPremiumReduction: 0,
    deductible: 0,
    maxOutOfPocket: 5500,
    copays: {
      primaryCare: "$0 copay",
      specialist: "$35 copay",
      urgentCare: "$35 copay",
      emergency: "$90 copay",
      inpatientHospital: "$300/day (Days 1–5)",
      outpatientSurgery: "$175 copay",
    },
    rxDrugs: {
      tier1: "$0 copay",
      tier2: "$5 copay",
      tier3: "$42 copay",
      tier4: "$95 copay",
      deductible: "$0",
      gap: true,
      initialCoverageLimit: "$5,030",
    },
    extraBenefits: {
      dental: { covered: true, details: "Comprehensive dental", annualLimit: "$2,500" },
      vision: { covered: true, details: "Annual exam + $250 eyewear" },
      hearing: { covered: true, details: "$1,500 hearing aid allowance" },
      otc: { covered: true, details: "$125/quarter OTC", annualLimit: "$500/year" },
      fitness: { covered: true, details: "Tivity Health gym membership" },
      transportation: { covered: true, details: "24 one-way trips/year" },
      telehealth: { covered: true, details: "$0 virtual visits" },
      meals: { covered: false, details: "Not covered" },
    },
    networkSize: 2100,
    enrollmentPeriod: "Oct 15 – Dec 7",
    effectiveDate: "Jan 1, 2025",
    serviceArea: "Jackson County, MO",
    carrierLogoColor: "#E8002D",
    carrierLogoTextColor: "#FFFFFF",
  },

  // ─── WellCare (4 plans) ───────────────────────────────────────────────────
  {
    id: "wellcare-value-1",
    carrier: "WellCare",
    planName: "WellCare Value Script (HMO)",
    planType: "HMO",
    contractId: "H5427",
    planId: "001",
    starRating: { overall: 3.0, label: "3 out of 5" },
    premium: 0,
    partBPremiumReduction: 0,
    deductible: 0,
    maxOutOfPocket: 7550,
    copays: {
      primaryCare: "$5 copay",
      specialist: "$50 copay",
      urgentCare: "$50 copay",
      emergency: "$120 copay",
      inpatientHospital: "$425/day (Days 1–5)",
      outpatientSurgery: "$275 copay",
    },
    rxDrugs: {
      tier1: "$0 copay",
      tier2: "$5 copay",
      tier3: "$42 copay",
      tier4: "$100 copay",
      deductible: "$0",
      gap: false,
      initialCoverageLimit: "$5,030",
    },
    extraBenefits: {
      dental: { covered: true, details: "Preventive dental", annualLimit: "$500" },
      vision: { covered: true, details: "Annual exam + $75 eyewear" },
      hearing: { covered: false, details: "Not covered" },
      otc: { covered: true, details: "$25/quarter OTC", annualLimit: "$100/year" },
      fitness: { covered: true, details: "Gym membership included" },
      transportation: { covered: false, details: "Not covered" },
      telehealth: { covered: true, details: "$0 virtual visits" },
      meals: { covered: false, details: "Not covered" },
    },
    networkSize: 1800,
    enrollmentPeriod: "Oct 15 – Dec 7",
    effectiveDate: "Jan 1, 2025",
    serviceArea: "Jackson County, MO",
    carrierLogoColor: "#00A651",
    carrierLogoTextColor: "#FFFFFF",
  },
  {
    id: "wellcare-classic-1",
    carrier: "WellCare",
    planName: "WellCare Classic (HMO)",
    planType: "HMO",
    contractId: "H5427",
    planId: "003",
    starRating: { overall: 3.5, label: "3.5 out of 5" },
    premium: 0,
    partBPremiumReduction: 0,
    deductible: 0,
    maxOutOfPocket: 6700,
    copays: {
      primaryCare: "$0 copay",
      specialist: "$45 copay",
      urgentCare: "$45 copay",
      emergency: "$90 copay",
      inpatientHospital: "$375/day (Days 1–5)",
      outpatientSurgery: "$225 copay",
    },
    rxDrugs: {
      tier1: "$1 copay",
      tier2: "$7 copay",
      tier3: "$45 copay",
      tier4: "$100 copay",
      deductible: "$0",
      gap: false,
      initialCoverageLimit: "$5,030",
    },
    extraBenefits: {
      dental: { covered: true, details: "Preventive + basic dental", annualLimit: "$1,000" },
      vision: { covered: true, details: "Annual exam + $100 eyewear" },
      hearing: { covered: false, details: "Not covered" },
      otc: { covered: true, details: "$50/quarter OTC", annualLimit: "$200/year" },
      fitness: { covered: true, details: "Gym membership included" },
      transportation: { covered: false, details: "Not covered" },
      telehealth: { covered: true, details: "$0 virtual visits" },
      meals: { covered: false, details: "Not covered" },
    },
    networkSize: 2000,
    enrollmentPeriod: "Oct 15 – Dec 7",
    effectiveDate: "Jan 1, 2025",
    serviceArea: "Jackson County, MO",
    carrierLogoColor: "#00A651",
    carrierLogoTextColor: "#FFFFFF",
  },
  {
    id: "wellcare-select-1",
    carrier: "WellCare",
    planName: "WellCare Select (PPO)",
    planType: "PPO",
    contractId: "H5427",
    planId: "007",
    starRating: { overall: 3.5, label: "3.5 out of 5" },
    premium: 0,
    partBPremiumReduction: 0,
    deductible: 0,
    maxOutOfPocket: 7550,
    copays: {
      primaryCare: "$5 copay",
      specialist: "$45 copay",
      urgentCare: "$45 copay",
      emergency: "$120 copay",
      inpatientHospital: "$400/day (Days 1–5)",
      outpatientSurgery: "$250 copay",
    },
    rxDrugs: {
      tier1: "$2 copay",
      tier2: "$8 copay",
      tier3: "$47 copay",
      tier4: "$100 copay",
      deductible: "$100",
      gap: false,
      initialCoverageLimit: "$5,030",
    },
    extraBenefits: {
      dental: { covered: true, details: "Preventive dental", annualLimit: "$750" },
      vision: { covered: true, details: "Annual exam + $125 eyewear" },
      hearing: { covered: true, details: "$500 hearing aid allowance" },
      otc: { covered: true, details: "$50/quarter OTC", annualLimit: "$200/year" },
      fitness: { covered: true, details: "Gym membership included" },
      transportation: { covered: false, details: "Not covered" },
      telehealth: { covered: true, details: "$0 virtual visits" },
      meals: { covered: false, details: "Not covered" },
    },
    networkSize: 2200,
    enrollmentPeriod: "Oct 15 – Dec 7",
    effectiveDate: "Jan 1, 2025",
    serviceArea: "Jackson County, MO",
    carrierLogoColor: "#00A651",
    carrierLogoTextColor: "#FFFFFF",
  },
  {
    id: "wellcare-ultra-1",
    carrier: "WellCare",
    planName: "WellCare Ultra (HMO)",
    planType: "HMO",
    contractId: "H5427",
    planId: "011",
    starRating: { overall: 4.0, label: "4 out of 5" },
    premium: 0,
    partBPremiumReduction: 0,
    deductible: 0,
    maxOutOfPocket: 5500,
    copays: {
      primaryCare: "$0 copay",
      specialist: "$40 copay",
      urgentCare: "$40 copay",
      emergency: "$90 copay",
      inpatientHospital: "$325/day (Days 1–5)",
      outpatientSurgery: "$200 copay",
    },
    rxDrugs: {
      tier1: "$0 copay",
      tier2: "$5 copay",
      tier3: "$42 copay",
      tier4: "$95 copay",
      deductible: "$0",
      gap: true,
      initialCoverageLimit: "$5,030",
    },
    extraBenefits: {
      dental: { covered: true, details: "Comprehensive dental", annualLimit: "$2,000" },
      vision: { covered: true, details: "Annual exam + $200 eyewear" },
      hearing: { covered: true, details: "$1,000 hearing aid allowance" },
      otc: { covered: true, details: "$100/quarter OTC", annualLimit: "$400/year" },
      fitness: { covered: true, details: "Gym membership included" },
      transportation: { covered: true, details: "12 one-way trips/year" },
      telehealth: { covered: true, details: "$0 virtual visits" },
      meals: { covered: false, details: "Not covered" },
    },
    networkSize: 2000,
    isNewPlan: true,
    enrollmentPeriod: "Oct 15 – Dec 7",
    effectiveDate: "Jan 1, 2025",
    serviceArea: "Jackson County, MO",
    carrierLogoColor: "#00A651",
    carrierLogoTextColor: "#FFFFFF",
  },

  // ─── Blue KC (4 plans) ────────────────────────────────────────────────────
  {
    id: "bluekc-select-1",
    carrier: "Blue KC",
    planName: "BlueMedicare HMO Select",
    planType: "HMO",
    contractId: "H3655",
    planId: "001",
    starRating: { overall: 4.0, label: "4 out of 5" },
    premium: 0,
    partBPremiumReduction: 0,
    deductible: 0,
    maxOutOfPocket: 5900,
    copays: {
      primaryCare: "$0 copay",
      specialist: "$40 copay",
      urgentCare: "$40 copay",
      emergency: "$120 copay",
      inpatientHospital: "$350/day (Days 1–5)",
      outpatientSurgery: "$200 copay",
    },
    rxDrugs: {
      tier1: "$1 copay",
      tier2: "$6 copay",
      tier3: "$44 copay",
      tier4: "$100 copay",
      deductible: "$0",
      gap: false,
      initialCoverageLimit: "$5,030",
    },
    extraBenefits: {
      dental: { covered: true, details: "Preventive + basic dental", annualLimit: "$1,000" },
      vision: { covered: true, details: "Annual exam + $150 eyewear" },
      hearing: { covered: true, details: "$500 hearing aid allowance" },
      otc: { covered: true, details: "$50/quarter OTC", annualLimit: "$200/year" },
      fitness: { covered: true, details: "Silver&Fit gym membership" },
      transportation: { covered: false, details: "Not covered" },
      telehealth: { covered: true, details: "$0 virtual visits" },
      meals: { covered: false, details: "Not covered" },
    },
    networkSize: 2900,
    enrollmentPeriod: "Oct 15 – Dec 7",
    effectiveDate: "Jan 1, 2025",
    serviceArea: "Jackson County, MO",
    carrierLogoColor: "#003087",
    carrierLogoTextColor: "#FFFFFF",
  },
  {
    id: "bluekc-choice-1",
    carrier: "Blue KC",
    planName: "BlueMedicare PPO Choice",
    planType: "PPO",
    contractId: "H3655",
    planId: "003",
    starRating: { overall: 4.0, label: "4 out of 5" },
    premium: 0,
    partBPremiumReduction: 0,
    deductible: 0,
    maxOutOfPocket: 7550,
    copays: {
      primaryCare: "$5 copay",
      specialist: "$45 copay",
      urgentCare: "$45 copay",
      emergency: "$120 copay",
      inpatientHospital: "$375/day (Days 1–5)",
      outpatientSurgery: "$225 copay",
    },
    rxDrugs: {
      tier1: "$2 copay",
      tier2: "$8 copay",
      tier3: "$47 copay",
      tier4: "$100 copay",
      deductible: "$0",
      gap: false,
      initialCoverageLimit: "$5,030",
    },
    extraBenefits: {
      dental: { covered: true, details: "Preventive dental", annualLimit: "$750" },
      vision: { covered: true, details: "Annual exam + $100 eyewear" },
      hearing: { covered: false, details: "Not covered" },
      otc: { covered: false, details: "Not covered" },
      fitness: { covered: true, details: "Silver&Fit gym membership" },
      transportation: { covered: false, details: "Not covered" },
      telehealth: { covered: true, details: "$0 virtual visits" },
      meals: { covered: false, details: "Not covered" },
    },
    networkSize: 3400,
    enrollmentPeriod: "Oct 15 – Dec 7",
    effectiveDate: "Jan 1, 2025",
    serviceArea: "Jackson County, MO",
    carrierLogoColor: "#003087",
    carrierLogoTextColor: "#FFFFFF",
  },
  {
    id: "bluekc-premier-1",
    carrier: "Blue KC",
    planName: "BlueMedicare HMO Premier",
    planType: "HMO",
    contractId: "H3655",
    planId: "007",
    starRating: { overall: 4.5, label: "4.5 out of 5" },
    premium: 0,
    partBPremiumReduction: 40,
    deductible: 0,
    maxOutOfPocket: 4000,
    copays: {
      primaryCare: "$0 copay",
      specialist: "$30 copay",
      urgentCare: "$30 copay",
      emergency: "$90 copay",
      inpatientHospital: "$250/day (Days 1–5)",
      outpatientSurgery: "$150 copay",
    },
    rxDrugs: {
      tier1: "$0 copay",
      tier2: "$4 copay",
      tier3: "$40 copay",
      tier4: "$90 copay",
      deductible: "$0",
      gap: true,
      initialCoverageLimit: "$5,030",
    },
    extraBenefits: {
      dental: { covered: true, details: "Comprehensive dental", annualLimit: "$3,000" },
      vision: { covered: true, details: "Annual exam + $250 eyewear" },
      hearing: { covered: true, details: "$2,000 hearing aid allowance" },
      otc: { covered: true, details: "$150/quarter OTC", annualLimit: "$600/year" },
      fitness: { covered: true, details: "Silver&Fit gym membership" },
      transportation: { covered: true, details: "24 one-way trips/year" },
      telehealth: { covered: true, details: "$0 virtual visits" },
      meals: { covered: true, details: "28 meals after hospital stay" },
    },
    networkSize: 2900,
    isBestMatch: false,
    isMostPopular: false,
    enrollmentPeriod: "Oct 15 – Dec 7",
    effectiveDate: "Jan 1, 2025",
    serviceArea: "Jackson County, MO",
    carrierLogoColor: "#003087",
    carrierLogoTextColor: "#FFFFFF",
  },
  {
    id: "bluekc-advantage-1",
    carrier: "Blue KC",
    planName: "BlueMedicare PPO Advantage",
    planType: "PPO",
    contractId: "H3655",
    planId: "010",
    starRating: { overall: 4.0, label: "4 out of 5" },
    premium: 59,
    partBPremiumReduction: 0,
    deductible: 0,
    maxOutOfPocket: 2900,
    copays: {
      primaryCare: "$0 copay",
      specialist: "$20 copay",
      urgentCare: "$20 copay",
      emergency: "$65 copay",
      inpatientHospital: "$175/day (Days 1–5)",
      outpatientSurgery: "$100 copay",
    },
    rxDrugs: {
      tier1: "$0 copay",
      tier2: "$3 copay",
      tier3: "$35 copay",
      tier4: "$80 copay",
      deductible: "$0",
      gap: true,
      initialCoverageLimit: "$5,030",
    },
    extraBenefits: {
      dental: { covered: true, details: "Full dental coverage", annualLimit: "$4,000" },
      vision: { covered: true, details: "Annual exam + $350 eyewear" },
      hearing: { covered: true, details: "$3,000 hearing aid allowance" },
      otc: { covered: true, details: "$200/quarter OTC", annualLimit: "$800/year" },
      fitness: { covered: true, details: "Silver&Fit + gym reimbursement" },
      transportation: { covered: true, details: "48 one-way trips/year" },
      telehealth: { covered: true, details: "$0 virtual visits" },
      meals: { covered: true, details: "56 meals after hospital stay" },
    },
    networkSize: 3400,
    enrollmentPeriod: "Oct 15 – Dec 7",
    effectiveDate: "Jan 1, 2025",
    serviceArea: "Jackson County, MO",
    carrierLogoColor: "#003087",
    carrierLogoTextColor: "#FFFFFF",
  },
];

export const POPULAR_RX_DRUGS = [
  { id: "rx-1", name: "Metformin", dosage: "500mg", frequency: "Twice daily", isGeneric: true },
  { id: "rx-2", name: "Lisinopril", dosage: "10mg", frequency: "Once daily", isGeneric: true },
  { id: "rx-3", name: "Atorvastatin", dosage: "20mg", frequency: "Once daily", isGeneric: true },
  { id: "rx-4", name: "Amlodipine", dosage: "5mg", frequency: "Once daily", isGeneric: true },
  { id: "rx-5", name: "Omeprazole", dosage: "20mg", frequency: "Once daily", isGeneric: true },
  { id: "rx-6", name: "Eliquis", dosage: "5mg", frequency: "Twice daily", isGeneric: false },
  { id: "rx-7", name: "Jardiance", dosage: "10mg", frequency: "Once daily", isGeneric: false },
  { id: "rx-8", name: "Xarelto", dosage: "20mg", frequency: "Once daily", isGeneric: false },
  { id: "rx-9", name: "Entresto", dosage: "49/51mg", frequency: "Twice daily", isGeneric: false },
  { id: "rx-10", name: "Ozempic", dosage: "0.5mg", frequency: "Weekly injection", isGeneric: false },
];

export const POPULAR_DOCTORS = [
  { id: "dr-1", name: "Dr. Sarah Johnson, MD", specialty: "Internal Medicine", npi: "1234567890", address: "4400 Broadway Blvd, Kansas City, MO 64111" },
  { id: "dr-2", name: "Dr. Michael Chen, MD", specialty: "Cardiology", npi: "2345678901", address: "2301 Holmes St, Kansas City, MO 64108" },
  { id: "dr-3", name: "Dr. Patricia Williams, DO", specialty: "Family Medicine", npi: "3456789012", address: "1000 Carondelet Dr, Kansas City, MO 64114" },
  { id: "dr-4", name: "Dr. Robert Martinez, MD", specialty: "Endocrinology", npi: "4567890123", address: "4320 Wornall Rd, Kansas City, MO 64111" },
  { id: "dr-5", name: "Dr. Lisa Thompson, MD", specialty: "Orthopedics", npi: "5678901234", address: "2800 Clay Edwards Dr, Kansas City, MO 64116" },
  { id: "dr-6", name: "Dr. James Wilson, MD", specialty: "Pulmonology", npi: "6789012345", address: "1 Hospital Dr, Kansas City, MO 64108" },
];
